

A public service announcement from the Tampa Bay Bandit Board RCPM


I am often asked, "What's a TWIT?" ...  my answer is:

                     {}==================={}
                     ||   A "TWIT" IS A   ||
                     {}==================={}

   Caller who keeps signing in with phony names to get another
   30 minutes before being asked to sign off.

   Caller who won't bother to TYPE the .INF (info) files to find
   out how to use the system properly.	 

   Caller who insists on TYPE'ing files endlessly, especially 
   useless ones, like the LASTCALR file, XMODEM.LOG, any programs 
   written in "C", and even *.*. 

   Caller who does endless DIR commands and never echoes anything
   to the printer.

   Caller who tries XMODEM R to send a file (about 50 times)

   Caller who keeps trying to XMODEM S RBBS.COM or other .COM files.

   Caller who doesn't know that CTRL-C aborts almost everything
   including DIR listings and tries every other key instead.

   Caller who repeatedly tries to TYPE .LBR files, and leaves 
   messages asking why the machine won't let him.

   Caller who tries something like this:

A0:SYSTEM>apple //e with a hayes card and cp/m
APPLE?
A0:SYSTEM>yes an apple //e, what's wrong with an apple?
YES?
A0:SYSTEM>yes, I said yessssss!!!!!!
YES?
A0:SYSTEM>list
LIST?
A0:SYSTEM>load
LOAD?
A0:SYSTEM>fre
FRE?
A0:SYSTEM>run
RUN?
A0:SYSTEM>menu
MENU?
A0:SYSTEM>exit
EXIT?
A0:SYSTEM>quit
QUIT?

++CARRIER LOST++
  
   and calls back several times each week to ask the same questions.

   Caller who leaves a message on RBBS and says you should have a 
   message program on the system so he can leave messages.
  
   Caller who discovers CHAT and tries 300 times in a row to summon 
   an operator even after being told, "Sorry operator is not available"

   Caller who tries every possible combination to change user areas 
   and just can't seem to remember to use the colon ":"

   Caller who leaves a message on RBBS asking SYSOP to please 
   leave out a copy of BASCOM.COM or MAC.COM ... etc

    Caller who leaves complaints on RBBS that he can't send you 
    his new universal debugger because XMODEM won't let him leave a 
    .COM file.

    Caller who, disgusted with his inability to use the system, 
    leaves a message to SYSOP telling him that he should try a really 
    good system, like the APPLE-based one in New York that has all 
    those really neat games on it.

    Caller who ignores repeated notices from SYSOP that system will be
    going down, then calls back immediately, and for the next 2 hours 
    only to be denied access each time.

    Caller who complains about the FREE service offered through the
    RCPM and tells you how you SHOULD run your system.

    Caller who ignores the fact that the SYSOP is trying to tell him
    something by typing on the screen and doing <returns> or CTRL-U's.


I MEAN LET'S FACE IT FOLKS, IT IS "OUR" MACHINES THAT YOU USE (ABUSE)
AND IN THE FINAL ANALYSIS, WE HAVE THE ON/OFF SWITCH ... NOT YOU.
