;;Patch: PATDDTZ
;;Date: June 6, 1988
;;Author: Bruce Morgen ("author" seems a bit strong here...)
;;Purpose: To create a DDT-style DDTZ 2.7 without reassembly.
;;This file patches the distribution copy of DDTZ27 to authentic
;;DDT-style commands instead of MS-DOS DEBUG commands.  While it
;;may be true that "most" CP/M users are also MS-DOS users, many
;;of these folks do not tinker under MS-DOS and are unfamiliar
;;with DEBUG, while few, if any,  CP/M users have forgotten DDT.
;;Use with EX or (if running Z3) ZEX 3.x, not tested with other
;;tools (NZEX, JOB/XJOB, SUBMIT/XSUB, etc.).  Produces
;;DDTZ27.COM from the distributed DDTZ27.CPM.
;;
ren patch.com=ddtz27.cpm
patch patch.com
e 1f6
71
.
e 1fa
71
.
e 1fe
e0
cd
.
e f61
9
e
.
e f69
b8
f
.
e f6d
e4
d
ea
d
.
e f73
9
e
.
e f79
1f
11
8d
10
86
11
.
e f81
e0
11
.
e f85
5
12
25
12
.
e 1ac1
20
.
e 1c90
aa
.
e 1dfe
87
87
.
n ddtz27.com
w
g0
ren ddtz27.cpm=patch.com
