\i1
\l1
\r64
BRADFORD.COM, the Near Letter Quality program by Aaron Contorer,
is a piece of "share-ware."  Only partial instructions come with
the program;  users should send $15 to the author to get an 18
page manual.

This file is an incomplete "cheat" file;  a list of BRADFORD
commands and (sometimes) what they do.  This is NOT intended to
keep Mr. Contorer from selling his instruction books.  I think
it will actually help, by showing there's much more to BRADFORD
than meets the eye.

This file only covers the "in-text" commands available. The menu
selections of the program should be self explanatory.

BRADFORD in-text commands consist of a command indicator, a two
letter command, and (sometimes) a numeric or character argument
(all run together, no spaces).  The command character is set by
the user when the program starts up;  generally "." is used. 
This is convenient for WORD STAR users.  Like WORD STAR,
BRADFORD commands stand alone on a line, starting in column 1.

===============================================================

Here's a partial list of BRADFORD commands.  "#" means command
takes numeric argument, "c" means character arg.  A "??" means
I haven't figured out how to use it.  And don't take my word for
anything, if you really want to know how to use BRADFORD, buy
the book.  This should make more sense to WORD STAR users:

.. Double command character: comment line, not printed

PA  ?? (new page?)

DM  ?? (define macro? wow, that would be slick!)

WK  ??

PS  ??

PN  ?? (start page numbering at #, would need #)

N1  ?? (number pages ON?)
N0  ?? (number pages OFF?)

OP  ?? (omit page number?)

WS  ??

PL  ?? (page length?  would require #)

CE  Center

CN  ?? (centering temporary OFF?)

JU  Justify
UJ  ?? (for WS compatibility, would need #?)

FL  ?? (footer line? kinda doubt it, no "header line" command)
LF  ?? (noticed a lot of these "reverse command" pairs)

FR  ??
RF  ??

RT  ??

ST# Strikes (darkness level 1-9)

DK  ??

CW# Character width 1-4

BN# ??

FN# Font change 1-8

P1  Proportional spacing ON
P0  Proportional spacing OFF

SF  ??

OK  ??

LX  ?? (extended left margin?  hanging indent?  would need #)
XL  ?? (temporary OFF?)

RX  ?? (extend right margin?
XR  ?? (temporary off?)

PO  ?? (that's letter O, not zero. see P0)

LM# Left Margin
ML  ?? (for WS?)

RM# Right Margin
MR  ??  (for WS?)

MT  ?? (top margin, for WS)
TM  ?? (top margin?)

MB  ?? (bottom margin, for WS?)
BM  ?? (bottom margin?)

DCc Define Control (see below)
CD  ?? (un-define control?)


Define Control is for defining extra printer controls.  It takes
two added characters.  First is the control you are defining,
second is what you are defining it to.  Some examples:

.dcC'
This line would be centered'

.dcL'
But this line would be left justified'

.dcB'
The .dcb switch defines the 'bold print toggle'

.dcU_
The .dcU switch defines the _underscore_ toggle

Normally you would set up any special DCs at the beginning of
your file.  There are probably more than the four shown in the
sample file, but I haven't found them yet.

When you select WORD STAR File and Justify from the front menu,
BRADFORD will only justify lines with "soft" carriage returns. 
It recognizes "hard" carriage returns as paragraph breaks.  The
.DCC and .DCL are handy for marking paragraph breaks in non-Word
Star documents.

===============================================================

BUGS & QUIRKS:

If a line is too long for specified margins, it will extend past
them -- sometimes BRADFORD has trouble justifying long lines.

If a line is too long for the page, it is cut off, not wrapped.

Soft hyphens sometimes give unpredictable results.

Here's a genuine bug, and it's hard to explain:  If you make a
mistake when giving a file name and the user area, BRADFORD can
get "lost" -- which might keep it from finding it's font files.
You have to see it happen to understand it; here's what I mean:

A> ; start here, in user area 0.  BRADFORD and fonts present.
A>BRADFORD
;
; sign on message
;
Name of file to print:  THISFILE.DOC
User Number [0-15]:     5              ;oops, I meant 4
;
; BRADFORD couldn't find it, so it asks again
;
Name of file to print:  THISFILE.DOC
User Number [0-15]:     4              ;that's better
;
; BRADFORD found the file, so we complete the dialog.
; but then (the plot thickens)
;
Printing copy 1...
Loading font...
<BEEP> Font not found, trying another font
<BEEP> No fonts, aborting
Warm Boot

A>; get the picture?

===============================================================

Wish list:

Default parameters at menu selections.

Parameter passing from command line.

===============================================================

WORD STAR is a trademark of Micro-Pro
BRADFORD is a trademark of Aaron Contorer and ConCom Enterprises

================

WORD STAR is a trademark of Micro-Pro
BRADFORD is a trademark of Aaron Contorer and ConCom Enterprises