SIGNS version 4.1
MakeFont version 2.3
22 Dec 86

There are now four libraries (or archives) to this set of 
programs: TSIGNS, ISIGNS, MSIGNS, and GSIGNS.  Generally 
speaking, TSIGNS contains a complete set of files for TurboPascal 
under CP/M-80, ISIGNS contains the complete set for MS-DOS, 
MSIGNS contains generic sources and executables [in Pascal MT+] 
for CP/M-80 (8080's), and GSIGNS contains generic sources and 
executables [in TurboPascal] for CP/M-80 (Z80).  Pick whatever 
you need, all can (generally-speaking) standalone.  

SIGNS is a program to make banners (down page) and signs (across 
page).  Written in TurboPascal, SIGNS allows lots of options:  
input from keyboard or file, output to screen, printer or file, 
change height and width of output, and printer control, all in an 
screen oriented format.  Generic versions are a bit less 
capabile and don't have fancy screen displays.

A separate program, MakeFont, is used to generate the random 
access fontfile used by SIGNS.  Three fontfiles are included, one 
of which will work only on the MS-DOS version (it's *BIG*).

The full-blown SIGNS is supplied in source code - it may have to 
be recomplied, preferably with TurboPascal.  If you don't have 
TurboPascal, you will have to get either of the GSIGNS or MSIGNS 
which contains two other versions: a stripped down version 
(MSIGNS) without all the fancy Turbo-Pascal-specific functions, 
(the executable COM file for CP/M-80 was done with DR's Pascal 
MT+ so it should run on 8080's and 8085's too) and a TurboPascal 
version (GSIGNS) that is very near to the full SIGNS but with the 
screen and printer controls stripped out (this executable COM 
file for CP/M-80 was done with TurboPascal, so it's probably Z80 
only.)

MS-DOS people have it a bit easier, ISIGNS contains both sources 
and executables.

The library name is only a mneumonic to remember the contents of 
each library, all are varients or different versions of the base 
'SIGNS'.  Contents are:

Archive: GSIGNS32.ARK CRC = 29 86 Generic Signs in Z80 CP/M (TurboPascal)
                Actual  Stored
Filename        Length   Size   
--------        ------  ------  
FONT1.DAT        12032    1595  \ two font files          
FONT2.DAT        12032    3297  /   (TSIGNS has source)   
GSIGNS32.COM     25856   18349  \ executable              
GSIGNS32.PAS     45696   18171  / source to generic signs 
MAKEFONT.COM     11136    9617  \ executable              
MAKEFONT.PAS      5894    2702  / source to font generator
----            ------  ------  
0006            112646   53731  

Archive: ISIGNS41.ARC CRC = 1B 87 Signs for IBM in MS-DOS (TurboPascal)

Filename        Length   Size 
--------        ------  ------
FONT1.ASC        10624    2357 \ small (10x12) font
FONT1.DAT        12000    1576 / 
FONT2.ASC        62464    6266 \ medium (20x40) font
FONT2.DAT        12000    3284 / 
FONT2.TST          256     206 input file to test font2
GOTHFONT.ASC    177408   21009 \ large (24x105) font
GOTHFONT.DAT     71040   12352 / 
GOTHFONT.FF     163200    9331 original font from 'gothic'
GOTHMASC.COM     12654   11919 \ convert horizontal format font to vertical
GOTHMASC.PAS      2284    1224 / 
GOTHMF.COM       14124   13045 \ makefont patched for large font
GOTHMF.PAS        5908    2721 /
GOTHSN.COM       34673   27969 \ signs patched for large font
GOTHSN.PAS       54699   20392 /
MAKEFONT.COM     14106   13032 \ create fonts (up to medium size)
MAKEFONT.PAS      5913    2720 /
POP.COM          14380   13148 \ make your machine go 'pop'
POP.PAS          10413    4280 /
SIGNS.IN           256     213 sample input
SIGNS.OUT        13440    3489 sample output
SIGNS.COM        34666   27917 \ signs for up to medium fonts
SIGNS.PAS        54694   20567 /
----            ------  ------
0022            781202  219017

Archive: MSIGNS12.ARK CRC = 04 15 Signs in Pascal MT+ (CP/M-80 generic)
                Actual  Stored
Filename        Length   Size 
--------        ------  ------
GFONT.ASC        10496    3788 \ small font file
GFONT.DAT        11904    3186 /
GMAKEFNT.COM     12416    6779 \ create dat files
GMAKEFNT.SRC      3712    1805 /
GSIGNS12.COM     32000   17838 \ signs
GSIGNS12.SRC     25984    9366 /
----            ------  ------
0006             96512   42762

Archive: TSIGNS41.ARK CRC = C1 57 TurboPascal Source for CP/M-80
                Actual  Stored
Filename        Length   Size 
--------        ------  ------
FONT1.ASC        10624    2357 small font
FONT2.ASC        62464    6266 medium font
FONT2.TST          143     143 test the medium font
MAKEFONT.PAS      5894    2702 create dat files from asc files
POP.PAS          10046    4145 self destruct?
SIGNS.IN           256     213 input file (font1 test)
SIGNS.OUT        13332    3485 output file
SIGNS.PAS        10305    3794 \
SIGNS0.PAS        5799    2615  \
SIGNS1.PAS        6827    2763   \
SIGNS2.PAS       10125    4031    \
SIGNS3.PAS        6691    2519     \
SIGNS4.PAS       15033    6020      \ source
----            ------  ------
0013            157539   41053

--> FILE:  SIGNS   .DQC         CRC = 80 27

The separate documentation file, SIGNS.DQC, contains lots more info.  
SIGNS.DOC is formatted to print pretty with WordStar - if control 
characters and print commands are not acceptable to your system 
run the file though a filter.  (FILT from Irv Hof is 
recommended.)

Bob Bloom
46 Broadleaf Drive
Newark, DE 19702

