
 #: 82351      Sec. 1 - General
Sb: #81955-#Commodore CP/M
    08-Mar-84  11:27:33
Fm: Joel Rubin 70007,576
To: Sysop David Kozinn   76703,565 (X)

In all fairness, it must be said that it is only $60 at discount
stores, including the co-processor card and distribution disk.
However, the disk format is not readily available, and software is not
readily available in it.  (although someone just converted modem7, and
vdo--an Osborne editor in xa1, here, and Nevada Fortran, Cobol, and
Turbo Pascal are available).  It is true that extensive work has to be
done to use a program like WordStar on it, and, considering the speed
of the 1541 disk drive (painfully slow) you might not want to.  Almost
any editor or modem program will require 6502 code to run (because
modem access is not through a Z-80 out instruction, but through 6502
NMI's, and because cursor addressing is done not through escape
sequences but through 6502 ROM calls).  One more problem is the amount
of RAM available. It is difficult to use more than 48K of RAM, although
you might be able to play with bankswitching on the 6510, and access 8K
more of isolated space.  (I think Data-20 does with their 80-column/Z-80
card which comes with SB-80; I don't know if they manage to map the
8K around so it appears not to be isolated).  The 8K is an O/S ROM,
used by the 6510 for I/O routines.  (nearly all I/O bios routines
switch the 6510 back in) (the other missing 8K is 4K of memory-mapped
I/O and the first 4K of the 6510 memory space, including zero page, O/S
vectors, and 1K for screen memory)
                Joel
                (CBM Sysop)
