The following messages provided the primary motivation for the release 
of UNARC 1.4.  These were posted on RCP/M Royal Oak (313-759-6569, 
Keith Petersen and Bob Clyne, sysops).

-----

Msg 088 is 08 line(s) on 11/17/86 from KEITH PETERSEN
to ALL about DRACO ARCS AND UNARC PROBLEM

Anyone who downloaded DRACO-1.ARC, DRACO-2.ARC and DRACO-3.ARC
please be patient.  The #2 and #3 ARCs won't extract properly
with UNARC on CP/M.  Bob Freed has been notified.  The files
will extract on MSDOS with PKXARC or ARC512.  I have left a
DRACO123.CRC file (made with my CRCK program) so you can be
sure you got a good download.  The files will be readable on
CP/M as soon as a fix is found for UNARC.
--Keith

-----

Msg 093 is 15 line(s) on 11/18/86 from BOB FREED
to KEITH PETERSEN about UNARC14.LBR ON THE WAY

Keith,
 
I want to thank you very much for the phone call last night.
I have identified and fixed the problem with UNARC12's handling of
those DRACO files.  (It only occurs with .ARC files created by
PKARC11 or higher -- not ARC512, PKARC10, or ARCA122.)  A new release,
UNARC14.LBR, will be forthcoming momentarily (as soon as I can cleanup
the documentation).  It also has some other improvements I think you
will like.
 
Feedback such as yours is very much appreciated and will always
receive a prompt response from me.
 
Regards,
Bob
