C REV. 23
C  ADVENTURES
        SUBROUTINE INSUB
      INTEGER VRBSIZ
       INTEGER*2 KTAB,LTEXT,STEXT,KEY,COND,ABB,ATLOC,PLAC,
     1 PLACE,FIXD,FIXED,LINK,PTEXT,PROP,ACTSPK,RTEXT,CTEXT,CVAL,
     2 HINTLC,HINTS,MTEXT,DLOC,ODLOC,ASCVAR
        LOGICAL DSEEN,BLKLIN,HINTED,YES,START
        LOGICAL TOTING,HERE,AT,BITSET,DARK,WZDARK,LMWARN,CLOSNG,PANIC,
     1       CLOSED,GAVEUP,SCORNG,DEMO,YEA
      INTEGER PBOTL,DUMMY
      INTEGER RTEXT,ASCVAR
      INTEGER KTAB,TABSIZ
      INTEGER ATLOC,LINK,PLACE,FIXED,HOLDNG
      LOGICAL BUF(128)
      INTEGER ITK(20)
      INTEGER MTEXT
      INTEGER PTEXT
      INTEGER ABB
      INTEGER WKDAY,WKEND,HOLID,HBEGIN,HEND,HNAME,
     1       SHORT,MAGIC,MAGNM,LATNCY,SAVED,SAVET,SETUP
      INTEGER LINUSE,TRVS,CLSSES,OLDLOC,LOC,CVAL,NEWLOC,
     1 KEY,PLAC,FIXD,ACTSPK,COND,HINTS,HNTMAX,PROP,TALLY,TALLY2,
     2 HINTLC,CHLOC,CHLOC2,DFLAG,DLOC,DALTLC,KEYS,LAMP,GRATE,
     3 CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,FISSUR,TABLET,
     4 CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,WATER,OIL,PLANT,
     5 PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,BEAR,MESSAG,VEND,
     6 BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,EMRALD,PYRAM,
     7 PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,DPRSSN,SAY,LOCK,
     8 THROW,FIND,INVENT,TURNS,IWEST,KNFLOC,DETAIL,ABBNUM,
     9 NUMDIE,MAXDIE,DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2
      INTEGER I,RTXSIZ,CLSMAX,MAGSIZ,LOCSIZ,CTEXT,STEXT,LTEXT,
     1 SECT,TRAVEL,TRVSIZ,TABNDX,OBJ,J,K,VERB,HNTSIZ,MAXTRS,
     2 HNTLOC,KK
        REAL LINES(15)
      LOGICAL TK,LIQ2,LIQ,LIQLOC,FORCED,PCT
      LOGICAL LTMP
        INTEGER TRAVEL(3,750)
      INTEGER VOCAB,RAN
        INTEGER KTAB(300)
      REAL ATAB(300)
C
      LOGICAL LLINES(60),CR,BL
C
        INTEGER LTEXT(150),STEXT(150),KEY(150),COND(150),ABB(150),
     1        ATLOC(150)
        INTEGER PLAC(100),PLACE(100),FIXD(100),FIXED(100),LINK(200),
     1        PTEXT(100),PROP(100)
        INTEGER ACTSPK(35)
        INTEGER RTEXT(205)
        INTEGER CTEXT(12),CVAL(12)
        DIMENSION HINTLC(20),HINTED(20),HINTS(20,4)
        INTEGER MTEXT(35)
        DIMENSION TK(20),DSEEN(6),DLOC(6),ODLOC(6),HNAME(4)
C
      COMMON /INCOM/ TRAVEL
        COMMON /TXTCOM/ RTEXT,LINES,ASCVAR
        COMMON /BLKCOM/ BLKLIN
        COMMON /VOCCOM/ KTAB,ATAB,TABSIZ
        COMMON /PLACOM/ ATLOC,LINK,PLACE,FIXED,HOLDNG
        COMMON /MTXCOM/ MTEXT
        COMMON /PTXCOM/ PTEXT
        COMMON /ABBCOM/ ABB
        COMMON /WIZCOM/ WKDAY,WKEND,HOLID,HBEGIN,HEND,HNAME,
     1       SHORT,MAGIC,MAGNM,LATNCY,SAVED,SAVET,SETUP
        COMMON /MISCOM/ LINUSE,TRVS,CLSSES,OLDLOC,LOC,CVAL,TK,NEWLOC,
     1 KEY,PLAC,FIXD,ACTSPK,COND,HINTS,HNTMAX,PROP,TALLY,TALLY2,
     2 HINTLC,CHLOC,CHLOC2,DSEEN,DFLAG,DLOC,DALTLC,KEYS,LAMP,GRATE,
     3 CAGE,ROD,ROD2,STEPS,BIRD,DOOR,PILLOW,SNAKE,FISSUR,TABLET,
     4 CLAM,OYSTER,MAGZIN,DWARF,KNIFE,FOOD,BOTTLE,WATER,OIL,PLANT,
     5 PLANT2,AXE,MIRROR,DRAGON,CHASM,TROLL,TROLL2,BEAR,MESSAG,VEND,
     6 BATTER,NUGGET,COINS,CHEST,EGGS,TRIDNT,VASE,EMRALD,PYRAM,
     7 PEARL,RUG,CHAIN,BACK,LOOK,CAVE,NULL,ENTRNC,DPRSSN,SAY,LOCK,
     8 THROW,FIND,INVENT,TURNS,LMWARN,IWEST,KNFLOC,DETAIL,ABBNUM,
     9 NUMDIE,MAXDIE,DKILL,FOOBAR,BONUS,CLOCK1,CLOCK2,
     1 CLOSNG,PANIC,CLOSED,GAVEUP,SCORNG
        COMMON /MISC2/ I,RTXSIZ,CLSMAX,MAGSIZ,LOCSIZ,CTEXT,STEXT,LTEXT,
     1 SECT,TRVSIZ,TABNDX,OBJ,J,K,VERB,HNTSIZ,MAXTRS,
     2 HINTED,HNTLOC,KK
C
      EQUIVALENCE(LINES(1),LLINES(1))
      DATA CR/X'0D'/,BL/' '/
      DATA KEY/150*0/
C
      CALL OPEN(7,'ATAB    DAT',1)
      N=1
      DO 3001 I=1,300,32
      K=MIN0(I+31,300)
C     DO 4001 IJ=1,2
4001  WRITE(7,REC=N)(ATAB(J),J=I,K)
3001  N=N+1
      ENDFILE 7
      CALL OPEN(8,'TRAVEL  DAT',1)
      N=1
      DO 3000 I=1,750,21
      K=MIN0(I+20,750)
C     DO 4000 IJ=1,2
4000  WRITE(8,REC=N)((TRAVEL(M,J),M=1,3),J=I,K)
      N=N+1
3000  CONTINUE
      ENDFILE 8
      CALL OPEN(9,'KTAB    DAT',1)
      N=1
      DO 3002 I=1,300,64
      K=MIN0(I+63,300)
C     DO 4002 IJ=1,2
4002  WRITE(9,REC=N) (KTAB(J), J=I,K)
3002  N=N+1
      ENDFILE 9
      CALL OPEN(10,'RTEXT   DAT',1)
      N=1
      DO 3003 I=1,205,64
      K=MIN0(I+63,205)
C     DO 4003 IJ=1,2
4003  WRITE(10,REC=N) (RTEXT(J), J=I,K)
3003  N=N+1
      ENDFILE 10
      CALL OPEN(7,'LTEXT   DAT',1)
      N=1
      DO 3004 I=1,150,64
      K=MIN0(I+63,150)
C     DO 4004 IJ=1,2
4004  WRITE(7,REC=N) (LTEXT(J), J=I,K)
3004  N=N+1
      ENDFILE 7
      CALL OPEN(8,'STEXT   DAT',1)
      N=1
      DO 3007 I=1,150,64
      K=MIN0(I+63,150)
C     DO 4007 IJ=1,2
4007  WRITE(8,REC=N) (STEXT(J), J=I,K)
3007  N=N+1
      ENDFILE 8
      RETURN
      END
