
[ From: Lillipute Z-Node, Chicago, Illinois - 03:04:09 AM  Apr 17, 1986 ]

Msg #4099 posted 04/12/86  by Richard Jacobson
To: JOHAN THOM     About: Kaypro Z3 Disks (31 lines)

In Z-News 407 Echelon announces a major new product - Bootable
Z-System Disks for Kaypro Computers.  These disks offer full
Z-System with the latest version of ZRDOS included (public
files) and three different versions of the Z-System, depending
on the level of power and the amount of TPA desired.  There is
a version that is FULL - it includes IOP provisions (very nice
with Echelon's newly announced BPRINTER - a printer spooler
that allows printing as a background task) - a version without
IOP, and a 'high TPA' version that does not include RCP's.
These disks are fully menu driven and load and go.  Put the
disk in drive A or the floppy drive of your 10 and hit the
reset button.  That's all.  Finally, these disks come with what
Echelon describes as the 'best written documentation thus far
offered,' an 80 page manual chock full of lucidly written, practical
instruction on using the power of the Z-System.  These disks and
the accompanying manual will be advertised in Byte, Micro C, Profiles, etc.
 
Now, what is the Sysop's opinion of this package?  It is great.
That is said from personal knowledge since the Sysop and Bruce
Morgen did the bootable disks and the manual.  In short, if you
don't like the disks or the manual, you got the authors right
here.  But you will like them.  I guaranty.
 
Cost is $69.95 for the entire package, including 3 Z-System
implementations, with ZRDOS, and the best book ever written
on the Z System from the perspective of the user.
 
A very worthwhile purchase.  Can be obtained from Echelon or
from here or from Bruce Morgen for $69.95 plus $4.00 for shipping
and handling.

