
       To Bruce Ratoff, Tom Churbuck, Keith Petersen


    Proposal For A Collaborate National CP/M User's Group

                     June 26, 1980

 I  would like to propose a merging of the "SIG/M" CP/M  User's 
Group  now in it's formative stages with "CP/M-NET  (tm)",  for 
the  purpose of public access (via modem) dissemination of CP/M 
compatble public domain software. Benefits to be derived to the 
"programming public at large" are:

1.0  Free  access to "professional quality"  software  for  the 
    price of a telephone call.

2.0  A "try before you buy" access of "commercial software"

3.0  Software "critique's" of "commercial software"

4.0   "language  access"  availability as a tutorial aid  to  a 
     better understanding of various languages (BASIC, FORTRAN, 
     COBOL,  PASCAL/UCSD,  PASCAL/M,  PASCAL/MT, PASCAL/Z, "C", 
     etc.).

5.0  A program "forwarding" network for "mass dissemination" of 
    software.

6.0    An  "on  going"  dialogue  of  "here's  how  to  do  it"  
     documentation,  for implementation of software (e.g.,  how 
     to  get MP/M running on your system...,etc.).  Believe me, 
     alot  of people out there are "baffled" at how to write  a 
     BIOS, or how to change I/O for various systems, etc.!


 These are just a view of my thoughts that have come to mind on 
this  issue,  and  I am sure that you could add quite a bit  to 
this...

 The  time and ability is certainly "at hand",  by evidence  of 
Keith  Petersen's system,  Tom Churbuck's  System,  the  Valley 
Computer  Club  system,  my system,  and other's...If we  could 
standardize  access  methods,   utility   formats,   etc.,   as 
"affiliate  systems",  we could offer quite a bit to the public 
"education" of the utilization of computers.

 I would be more than willing to be the "West Coast"  affiliate 
system, and help in all details of this proposed project.

 Additionally,  we  might  publish a quarterly  "news  letter", 
requiring  possibly  a  $12 per year membership  fee  to  cover 
expenses  of  system  operation  and  maintenance.  Of  primary 
interest  to me,  is to make public domain software PUBLIC! Not 
under  the  control  of  profit  making  organization  such  as ŠLifeboat (read Tony Gold here...) that (in general) have little 
professional  software  to  offer  in  their  control  of   the 
CPMUG/Lifelines  "racket",  much less some of the really "crap"  
commercial software like "BSTAM"! (WOW, did I say that?!?).

 Also,  I  suspect that if "SIG/M" really gets  "rolling",  you 
will  have your hands full with the logistics  of  distributing 
"physical   diskettes"   to  the  public...my  proposal   would 
certainly take care of any problems in that area.

 To conclude,  give this some thought as what we "collectively" 
might do...leave any correspondence on this matter on my system 
or Tom Churbuck's system as an "open forum".

                              Best Regards,

                              Kelly Smith, CP/M-NET (tm)
                              3055 Waco Avenue
                              Simi Valley, California, 93065
                              (805) 527-9321 (300 Baud Modem)
                              (805) 527-0518 (Verbal)

 
 
