title	byex.mac  version 1.0
;	BYEX.MAC, part of the SIGNON Subsystem by Dick Lieber
;	Refer to SIGNON.DOC for details
;
;	This is the interface for returning to bye from
;	the SIGNON Subsytem exit program EXIT.BAS
;
;	EXIT.BAS is normally executed as BYE.COM
;
;	Thanks to Ben Bronson for the byex scheme used in RBBSEXIT.BAS

;	byeloc is set to the runtime starting address of your BYExx.ASM
;	program


byeloc	equ	0f800h

	entry	byex

byex:	jmp	byeloc
	end
