	SIG/M Volume 000 is a Dynamic Directory of all SIG/M software
volumes. Included on the volume is the program 'FIND' to enable you to
rapidly locate programs or disks. As new volumes are added to the library,
Volume 000 is updated. Another valuable program on the disk is a list of
all of the distribution points for SIG/M software. It also is updated as
changes take place, but since we had a few K left on this disk - and it 
being the first for the year 1984 - we thought we would include it to
enable computer users to find the most convenient places to get SIG/M
software (and to encourage those is areas where we have no coverage to
become distributors).



                     Regional Distribution Areas            

                       Worldwide Headquarters

             SIG/M                             SIG/M 
          P.O.Box 2085           or         P.O. Box 97
      Clifton, NJ 07015-2085            Iselin,   NJ   08830

Northeast Region                   
     Dave Mitton                   
     NECS                          
     Andover,  MA                  

Atlantic Region 
     Bill Earnest
     Lehigh Valley Computer Club
     Allentown, PA
 
Mid Atlantic Region                
     Stan Levine                                      
     CPMUG of Washinton DC    
     Arlington, VA                                    

Southeast Region
     Charlie Wells                      John Irwin
     Atlanta Computer Society           Miami Amateur Computer Group
     Atlanta, GA                        Miami, FL

North Central Region               
     Keith Petersen                     Jim Mills
     Royal Oaks, MI                     CACHE/CPMUG
                                        Glen Ellyn,  IL
     Dave Hardy
     Technical CBBS
     Grosse Point, MI

South Central Region 
     Al Whitney                         Fred Pfafman
     Houston Area                       Texans Computer Club
     Sugarland, TX                      Plano, TX
                                        Dallas Area
Northwest Region                                    
     A.J. Lundquist                     Jorge Blat           
     Denver Amateur Computer Soc.       CPMUG of Puget Sound
     Bloomsfield, CO                    Edmonds, WA
     
Southwest Region
     Charlie Foster                     Trevor Marshall 
     Pascal/Z Users Group               Thousand Oaks RBBS
     Sacramento, CA                     Thousand Oaks, CA

Eastern Canada                     Western Canada
     Jud Newell                         Dave Bowerman
     Toronto RCP/M                      Northwest Computer Society
     Toronto, ONTARIO                   Vancouver, BC

Asia                               Western Europe
     Bill Bolton                        Derek Fordred
     Software ToolWorks                 CP/MUG of U.K.
     Sidney, NSW                        Dartford, Kent
     Australia                          England  U.K.

Carribean                          Middle East
     *** Open ***                       *** Open ***
    
                       Northeast Region

Maine

Massachusetts

     Dave Mitton                        Voice (617)646-3080
**** SIG/M - Northeast Region
     NECS New England Computer Society
     13 Swan St  	                CBBS  (617)646-3610
     Arlington,     MA   02174          

     Mark Fishman
     Boston Computer Society
     51 Grandview Road
     Arlington, MA   02174

     Doug Fuller                        Voice (413)589-7490
     TBBS 
     Interstate Business Computers
     Ludlow,    MA   01056
 
New Hampshire

     Steve Peterfreund                  Voice (603)888-9900
     MicroProcessor Associates          CBBS  (603)888-4488
     Box 3438                           DEC VT-180/Rainbow,
     Nashua,    NH   03061              Heath/Zenith, etc.

Rhode Island
     Dean Kelchner         
     11-B Sandy Point Farm
     Portsmouth, RI      02871 

Vermont
   
                         Atlantic Region

Connecticut

     Henry B. Rothberg                  Voice (203)397-0041
     Laticrete Intl., Inc.               days (203)393-0010 x202
     1 Laticrete Park North
     Bethany, CT   06525                8in,Kaypro,Vector,N*
   
Delaware

New Jersey

     ACG-NJ  Amateur Computer Group of NJ
**** SIG/M - Main Hqtrs
     P.O.Box 97                         RBBS  (201)272-1874
     Iselin,        NJ   08830          RBBS  (215)398-3937

     Randy Reitz                        Voice (201)635-5642
     ACG-NJ Northstar Users Group
     26 Maple St     
     Chatham Twp,   NJ                  N*,8in

     Kevin O'Connell                    Voice (609)461-4351
     RCA - VM Systems
     Cherry Hill,   NJ

     Steve Leon                         Voice (201)886-1658
**** SIG/M - Disk Editor                     
     200 Winston Drive
     Cliffside Park,NJ 07010

     Bill Chin                          Voice (201)778-5140
**** SIG/M - Chairman Operations & Policy
     177 Hadley Ave                     8in,IBM-PC,VT-18X
     Clifton,       NJ   07011          

     Bruce Ratoff                       Voice (201)272-1793            
**** SIG/M - SysOp                      CBBS  (201)272-1874             
     ACG-NJ Club President
     26 Broad St.                       Epson-HX10
     Cranford,      NJ             

     Gilbert Linn                       Voice (201)763-6974
**** SIG/M - Catalog Distribution
     28 Midland Boulevard
     Maplewood,     NJ   07040     

     Sol Libes                          Voice (201)277-2063
**** SIG/M - Catalog Editor
     P.O.Box 1192 
     Mountainside,  NJ   07092

     Raymond Glueck                     Voice (201)227-5362
**** SIG/M - Compuserve Liason
     ACG-NJ  Micropolis Users Group
     1 Rutledge Road                    8in,SSSD/DD,Vector
     Pine Brook,    NJ  07058           Micropolis

     Ken Tompkins                       Voice (609)652-1776x497
     Stockton Computer Group 
     Stockton State College
     Apple Microlab
     Pomona,        NJ   08240                                 

     Dave Raibert                       Voice (201)444-4600
**** SIG/M - Treasurer
     10 Wilsey Square
     Ridgewood,     NJ 07450

     Bill Woythaler                     Voice (201)273-3955
     296 Summit Avenue
     Summit,        NJ   07901          N* (Northstar)

     Bruce Blakeslee                    Voice (201)233-3185
**** SIG/M - Information Secty
     906 Crestwood Road West
     Westfield,     NJ   07090

     Glenn Dusch                        Voice (201)233-6292
**** SIG/M - Order Processing
     Westfield,     NJ 07090

     Gardner Harris                     Voice (201)731-6271
     ACG-NJ Morrow MicroDecision Librarian
     West Orange,   NJ

New York

     Henry Kee                          Voice (212)539-3202
**** SIG/M - Librarian      
     NYACC-New York Amateur Computer Club
     42-24 Colden St                    8in,Cromemco,IBM-PC,
     Flushing, NY   11355               Osborne,Kaypro,VT-18X

     Gerald Harrison                    Voice(516)822-1697
     LICA-Long Island Computer Association
     36 Irene Lane East                 CBBS (516)561-6590
     Plainview,     NY   11803          ABBS (212)448-6576

Ohio

     J.C. Kramer                        Voice (614)279-8271
     CP/M - ACSCO of Columbus
     P.O.Box 28355                      Osborne,Xerox,Omikron                  
     Columbus, OH   43228-0355          

     Charles E. Lewis			Voice (216)666-5982
     Cleveland Digital Group            RCPM  (216)645-0827
     379 South Hametown Road
     Copley, OH     44321

     Dave Robling                       Voice (513)258-2218
     Dayton Microcomputing Soc.         CBBS  (513)435-5201
     2629 Ridge Ave
     Dayton,   OH   45414

Pennsylvania

     William Earnest                    Voice (215)398-1634
**** SIG/M - Atlantic Region & SysOp
     Lehigh Valley Computer Group
     RD#1  Box 830
     Orefield,     PA   18069           CBBS  (215)398-3937

     Robert  Todd                       Voice (215)752-4604
**** SIG/M - Regional Distribution Coordinator
     ACG-NJ Zenith/Heath Users Group    
     Philadelphia Amateur Computer Society
     1121 Briarwood
     Bensalem,      PA   19020          H-89,8in,
 
     Jim Woolsey                        Voice (215)862-5806
     Delaware Valley Computer Club
     6 Stone Hill
     New Hope,      PA                  

                       Mid-Atlantic Region

Kentucky

Maryland

North Carolina

     Elliot Wheeler                    Voice (704)827-6751
     P.O. Box 308                      Telex 802025 GASDY MTHY
     Stanley,    NC   28164  

South Carolina

Tennessee

Virginia

     Stan Levine                        Voice (703)522-1192
**** SIG/M Mid-Atlantic Regional Coordinator
     CP/M Users of Washington DC
     2053 N. Abingdon Street
     Arlington,     VA   22207

     Sam Hunt                           Voice (703)323-7627
     Metro Washington CPMUG
     4711 Olley Lane
     Fairfax,       VA   22032          

     Jack Williams                      Voice (703)371-5474
     Microcomputer Investors Association
     902 Anderson Drive
     Fredricksburg,      VA   22405

     David C.E. Holmes                  Voice (804)898-5913
     Digital Interest Group in Tidewater
     P.O.Box 1708                       RBBS  (804)898-7493
     Grafton,       VA   23692          24hr,PMMI,4MB 

     Fred W. Davis                      Voice (703)384-6871
     Route 4 Box 50
     Salem,         VA   24153

     Christopher Leithiser              Voice (703)569-8037
     Washington Apple Pi
     8646 Reseca Lane
     Springfield,   VA   22152          8in,Apple][                 

West Virginia

                        Southeast Region
Alabama

Florida

     John Irwin                      Voice (305)271-4592
**** SIG/M Co-regional Coordinator
     Miami Amateur Computer Group
     9159 South West 77th Avenue
     Miami,        FL   33156
 
     Mike Niswonger                  Voice (904)244-1346
     CPMUG of South Oklaloosa County
     541 East Miracle Street
     Mary Esther,  FL   32569

     Robert Tate                        Voice (305)830-7319
     Central Florida Computer Society         (305)831-6049
     805 Turnbull Ave
     Altamonte Springs, FL 32701

Georgia

     Allen V. Cleveland                 Voice (404)252-1879
     Atlanta Computer Society
     1225 Spring Mill Court NE
     Atlanta,  GA   30319

     Charlie Wells                      Voice (404)993-0366
**** SIG/M - Southeast Region
     Atlanta Computer Society           CBBS  (404)636-6130 212
     465 Northgate Pass                 CBBS  (404)394-4220 212
     Roswell,  Ga   30075

Mississippi
   
                      North Central Region

Illinois

     Roland Friestad                    Voice (309)343-0629
     Knox County Computer Club
     RR 1, Box 163
     Cameron,       IL   61423

     Jim Mills                          Voice (312)469-2596
**** SIG/M Co-regional Coordinator      RCPM  (312)298-2597
     CACHE/CPMUG
     Glen Ellyn,    IL  60138
     or
     c/o Adage Corp.                    Voice (312)932-7377
     17W725 Butterfield Rd. Suite C
     Oakbrook Terrace, IL 60181

     Stanley Hanson                     Voice (312)469-3246
     Northrop Microcomputer Users Group
     182 East Road                      Omikron,TRS-80,8in
     Glen Ellyn,    IL   60137          SSSD,DD
        
Indiana

Iowa

Michigan

     Keith Peterson                     
**** SIG/M - North Central Region
     P.O.Box 309
     Clawson,       MI   48017          CBBS  (313)759-6569

     Dave Hardy                         Voice (313)885-0506
**** SIG/M - Co-regional Coordinator
     Technical CBBS                     Voice (313)846-8000
     736 Notre Dame                     CBBS  (313)846-6127
     Grosse Pointe, MI   48230          
     or
     CDP Corp.
     5151 Miller Road
     Dearborn,      MI   48126          Voice (313)846-1055

     Kenneth Jackson                    Voice (313)353-8660
 c/o CyberSource                          or  (313)422-8585
     24000 Telegraph Road
     Southfield,    MI   48034          Televideo            

Minnesota
  
Missouri

Nebraska

North Dakota

South Dakota

Wisconsin

                      South Central Region

Arkansas

Kansas

Louisiana

     Homer Branch                       Voice (504)891-4951
     Heath UG of New Orleans
     703 Valence
     New Orleans,   LA   70115     

Missouri

Nebraska

New Mexico

Oklahoma

Texas

     Al Whitney                         Voice (713)342-5139
**** SIG/M  - South Central Region
     1203 Austin Colony                 CBBS  (713)469-8893
     Sugarland, TX   77469              8in,IBM-PC,Televideo

     Fred Pfafman                       Voice (214)596-5034
**** SIG/M - Co-regional Coordinator 
     Texans Computer Club
     2320 Heather Hill Lane
     Plano,         TX   75075          

     Charles Sanborne
     Houston Area RBBS                  CBBS (713)469-8893
     SATSUMA
     Houston,       TX   

New Mexico

                        Northwest Region

Alaska

Colorado

     Jack Riley                         Voice (303)494-8342
     Denver Amateur Computer Society 
     Boulder,       CO                  CBBS  (303)499-9169

     A.J. Lundquist                     Voice (303)466-7938
**** SIG/M - Northwest Region
     Denver Amateur Computer Society    CBBS  (303)499-9169  212A,32MB
     P.O.Box 633                        CBBS  (303)985-1108  212A,16MB
     Broomfield,    CO   80020          CBBS  (303)642-3034  212A,16MB

Hawaii

     James Yuen                         Voice (808)262-2845
     919 Luna Helu St.
     Kailua,        HA   96734

     Dr. Victor M. Mori                 Voice (808)955-6683
     Aloha Computer Club
     2525 South King St - suite 303
     Honolulu,      HA   96826   

Idaho

Montana

Oregon

Utah

Washington
   
     Jorge Blat                         Voice (206)771-1408
**** SIG/M Co-regional Coordinator      
     CPMUG of Puget Sound               CBBS  (206)621-8665 212A, 14MB
     8016 188th SW                                      
     Edmonds,       WA   98020          

     Anchor Electronics                 CBBS (206)621-8665
     Seattle,       WA                   

     Dick Joslin                        Voice (206)244-8558
     Northwest Computer Society
     P.O. Box 68374
     Seattle,       WA   98188 

     Tim Linehan                        Voice (206)357-7400     
     Olympia RCPM                       CBBS  (206)352-7530
     Olympia,  WA                       PMMI,24hr,16MB
   
     David Rabbers                      Voice (206)784-2719
     Ballard CP/M Users Group
     6551 16th Ave NW     
     Seattle,       WA   98117

Wyoming

                        Southwest Region

Arizona

California

     Richard Mason                      Voice (714)746-4832
     San Diego Computer Society
     1037 Park Hill Lane
     Escondido,     CA   92025          
   
     Mark Sheppard                      Voice (408)267-1218
     INSUA - Int'l Northstar Users Assn
     P.O. Box 2789                      8", N* 
     Fairfield,     CA   94533
                              
     Sam Lay                            Voice (714)842-6588
     South Orange County Computer Club
     6771 Bonnie Drive
     Huntington Beach, CA   92647

     Jim Ayers                          Voice (415)383-0473
     Apple CPMUG of Small Computer Users of Marin
     301 Poplar St.                     CBBS  (415)383-0473
     Mill Valley,   CA   94941          5pm-8am,8in,Apple,Otrona

     Charlie Foster			Voice (916)392-2789
     JRT Pascal & Z Users Group
**** SIG/M - Southwest Region   
     7962 Center Parkway
     Sacramento,    CA   95823          CBBS  (916)483-8718

     Don Bozarth                        Voice (916)363-5544
     John Moorhead                      Voice (916)758-2495
     S.M.U.G. - Sacramento Microcomputer Users Group         
     P.O.Box 161513                     CBBS  (916)483-8718
     Sacramento,    CA   95816     

     Harry F. McGrew                    Voice (805)687-7121
     Santa Barbara Computer Club
     747 Calle de Los Amigo             RBBS  (805)682-7876
     Santa Barbara, CA   93105               

     Michael J. Karas                   Voice (805)527-7922
     Valley Computer Club
     2468 Hansen Court
     Simi Valley,   CA   93065

     Kelly Smith                        Voice (805)527-0518
     CP/M - NET
     3055 Waco Ave                      CBBS  (805)527-9321
     Simi Valley,   CA   93063          7pm-7am,PMMI,Osborne
                                        Kaypro

     Trevor Marshall			Voice (805)492-3693
**** SIG/M Co-regional Coordinator
     Thousand Oaks - RBBS		RBBS  (805)492-5472
     3423 Hill Canyon Avenue            24hr,1200bps,PMMI,10MB,160MB
     Thousand Oaks, CA   91360

Nevada

                    General Computer Networks

     CompuServe R SIGS(CP-MIG)

     Charlie Strom,      New York,      NY   Voice (212)982-2237

     Tom Jorgenson, 

     Dave Kozinn         Los Angeles,   CA
   

                International Distribution Areas

                         Far East Region

Republic of China

Japan

     Fukuoka Toshio                   Voice V-01-44-36-2807
     Futabacho 1-15-4
     Tomakomai, Hokkaido  Japan

Australia

     Paul Taylor                        CBBS 09-459-3837
     Perth, Autralia                    CCITT 300 bps Modem
     
     Bill Bolton                        Voice 61-2-997-1018
**** SIG/M - Far East Region            CBBS  61-2-997-1836
     P.O. Box 80                        local (02) 997-1836
     Newport Beach                      CCITT 300 bps Modem
     NSW, 2106
     Australia

     Archive Computer Services
     23 Wagners Rd.
     Clayfield
     QLD, 4011
     Australia

     Melbourne Microcomputer Club       CBBS  61-3-762-5088
                                        local (02) 762-5088

     Telcom Australia                   RCPM  61-2-663-0138
     Micro Design Lab                   local (02) 663-0138

     Mi Computer Club                   BBS   61-2-662-1686
                                        local (02) 662-1686

Philipines
Singapore

     Alex Chan
     745 Mountbatten Road
     Singapore  1543
 
     Naresh Kapoor
     Patel Computer Systems PTE
     27058  OCBC Centre
     Chulia St
     Singapore 0104
    

                      Western Canada Region

Alberta

British Columbia

     Dave Bowerman                      Voice (604)937-3148
**** SIG/M - Canada Northwest Region    
     West Coast Computer Society        CBBS  (604)937-0906
     P.O.Box 4031
     Vancouver,     B.C. V6B3Z4         8in,DSDD,2MB,PMMI
or
     2058 Highview Place
     Port Moody,    B.C. V3H1N5

Manitoba

Northwest Territories

Saskatchewan

     Bob Stek
     R.O.M.S.
     19 Mayfield Road
     Regina,   Canada    S4V0V7

Yukon

                      Eastern Canada Region

Newfoundland

Nova Scotia

Ontario

     Judson Newell                      Voice (416)239-2835
**** SIG/M - Canada Northeast Region    CBBS  (416)231-9538
     4691 Dundas St. - W                          or
     Islington,    Ontario                    (416)231-1262

Quebec
                      Western Europe Region  
Africa
     Peter Briggs
     Transvral Amateur Computer Club
     P.O.Box 2513
     Kempton Park   1620                Zenith series
     South Africa   
Austria

Belgium

France

Germany

Italy

Netherlands

     Hank Berkhoudt
     CP/M Groep
     Hesselskamp 4
     3085 SM 
     Rotterdam,     Netherlands

Portugal

Spain

Switzerland

United Kingdom

     J.D. Millne                        Voice (011-44)0670-827480
     Inpholink, Ltd
     Front Street West                  Sirus/Victor 9000
     Bedlington, Northumberland
     England   NE22 5UB

     Derek Fordred                      Voice (011-44)0322-22669
**** SIG/M - Western Europe
     CP/M Users Group of UK
     72 Mill Road
     Hawley
     Dartford, Kent 
     England   DA2 7RZ
   
                      South America Region


     John Irwin                        Voice (305) 271-4592
**** SIG/M - South American Coordination
     Miami Amateur Computer Group
     9159 South West 77th Avenue
     Miami,    FL  33156
Argentina

Brazil

Peru
Venezuela

     Hans Stauffer                      Voice (011-58)2-987-3308
     Caracus Computer Club
     Apartado 66394
     Caracus,  Venezuela 1061A
           Or
      Hans Stauffer  M-105
     Jet International Airport
     P.O.Box 520010
     Miami,    FL   33159





 
 