
Date: Friday, 17 February 1984  09:54-MST
From: King Ables <ables at ut-ngp.ARPA>
To:   h19-people at mit-mc.ARPA
Re:   solution to my H89 problems

Well after hearing from people who seems to know as much or
more about H89s than Heath and after calling Heath again, I
think I have solved the problem.

When I ordered CP/M the first time and it didn't work, I called
Heath and they said "Oh, yeah, you need a hardware upgrade!"
So I did the following:

1) Replaced the 444-42 in U517 with a 444-66
2) Connect a jumper from the middle pin of U503 to pin 17 of P509
They assured me this would work.  However, to make the full upgrade,
I could also do:
3) Replace the 444-40 in U518 with a 444-62
4) Replace the 444-43 in U550 with a 444-61
If I did this, I would lose cassette capability.  Since this wasn't
necessary (they said) I decided to just do 1 & 2.

When I did this and it still didn't work, I called Heath again.  They
said it should have worked and my disk must be bad.  So they sent me
a new disk..guess what, still didn't work.  Then they say hardware
problem with the disk drive.  That's when I put my problem on the net.
Mr. D. C. Finch of Phoenix was kind enough to write me a letter
(they have R/O access to the net) which told me that indeed 3 & 4
were necessary (at least for CP/M 2.2.03 and later).  So this morning
I called Heath again and they said, "That's right, you have to replace
all three chips!"  Just wish they had said that back in November!!
I'll be happy to give anyone the details of Mr. Finch's letter if
asked, I don't think most people are that interested.

Thanks to all those who replied, I am convinced that people on the net
are more valuable than Heath's consulting department.  At least
I get a correct answer the first time on the net!  Too bad Heath
doesn't list hardware upgrades and long distance charges in their
catalog along with the price of the item!

--King Ables
USMail: Computation Center, Univ. of Texas, Austin, Texas  78712
ARPA:   ables@ut-ngp
UUCP:   {ctvax,ihnp4,kpno,seismo}!ut-sally!ut-ngp!ables
