
                          The Trenton Z-Fest 1993
                          -----------------------

   The Z-Fest in connection with the 1993 Trenton Computer Festival (TCF)
will take place again this year in the banquet room at the Stage Depot
Motel, beginning late in the afternoon on Saturday, April 17, and ending
Sunday morning, April 18.

   On Saturday morning we will have our formal session as part of the
Trenton Computer Festival at Mercer County Community College.  I know that
Bruce Morgen, Hal Bower, and Jay Sage are on the schedule.  After the formal
presentations, those participating in the Z-Fest will adjourn to the Stage
Depot Motel for informal discussions and socializing.  No formal technical
presentations are planned.  We will have food and beverages brought in and
can stay as long into the night as our stamina permits.  We may even succeed
this year in staging the Anchovy-Pizza-Eating Contest that had to be
scuttled last year due to the unfortunate unavailability of anchovies (watch
out Lee Bradley -- I am already in serious training for this event).  We
will ask for contributions to cover the cost of the room and food.

   The banquet room will be available Sunday morning as well for those who
did not get enough talk in on Saturday night (or who are still there from
Saturday night!).  Most people then head over to the TCF flea market.

                            Lodging Information
                            -------------------

   The Stage Depot Motel provides not only convenient but also low-cost
lodging.  The management has informed me that there will be a square dance
festival taking place in the local area and that rooms will be in short
supply.  Therefore, I urge you to make reservations just as soon as you can. 
Here is the information about the motel.  Please mention that you are with
the Z-Fest when you place your reservations.  Also note that the
registration lobby closes at 11 PM.  If you will be arriving later, special
arrangements have to be made.  The room rates below include taxes.

        Stage Depot Motel            room with 1 double bed
        Route 31                        1 person     $39.22
        Pennington, NJ                  2 people      46.64
        609-466-2000                 room with 2 double beds
                                        1 person     $46.64
                                        2 people     $49.82
                                        3 people     $53.00
                                        4 people     $56.18

   At a later time I will post a message with an ASCII map showing how to
find the motel and the TCF site.  For those who wish to try locating them on
a roadmap, the motel is on Route 31 north of the city of Trenton and, I
would guess, about 5 miles north of I295.  Mercer County Community College
is on Route 535 east of the city of Trenton and east of I295, in or near the
town of Mercerville.

   If you are planning to come, please let me know by any of the following
means:

        Internet mail to:               SAGE@LL.MIT.EDU
        GEnie mail to:                  JAY.SAGE
        a message on my Z-Node:         617-965-7259 (pw=DDT)
        a message on my DOS BBS:        617-965-7046
        a FAX to me at work:            617-981-5328
        real postal mail to:            1435 Centre Street
                                        Newton, MA  02159-2469

Hope to see lots of you there!

                                        Jay Sage
