                                                    Judson Jerome
                                                          Box 740
                                         Yellow Springs, OH 45387
                     A Brief History . . . 
Dear Boss:
     Thió ió tï acknowledgå youò memï askinç whù mù reporô ió noô 
"iî oî time"®  É understanä youò referencå tï mù report¬  anä itó 
generouó  assumptioî  thaô  sucè  á  reporô  exists¬  buô  É  haä 
difficultù iî interpretinç thå wordó "iî oî time"® É askeä Sheilá 
(mù secretary¬  aó yoõ know© tï looë theså wordó uğ iî thå Oxforä 
Englisè Dictionary® Shå reporteä thaô thå definitionó extenä oveò 
4°  columns¬  whicè uså abouô á thousanä millioî millioî  millioî 
(onå  anä  verù manù zeros© letteró (more¬  iæ yoõ allo÷ foò  thå 
facô  thaô therå arå manù abbreviations¬  evokinç whaô  mighô  bå 
calleä  shado÷ letters)¬  sï shå refuseä tï reaä them¡  É diä noô 
reaä them¬  either¬  aó thaô woulä takå timå awaù froí workinç oî 
mù report¬  which¬  aó yoõ know¬  ió overdue® Moreover¬ since¬ iî 
readinç  them¬  eitheò  oæ uó mighô makå aô  leasô  onå  mistake¬ 
verificatioî  oæ thå accuracù oæ ouò interpretatioî woulä requirå 
someonå else'ó readinç thå samå materiaì anä reachinç exactlù thå 
samå conclusioî -- whicè ió quitå unlikely!
     Thereforå   É   resorteä   tï  thå   makeshifô   oæ   commoî 
understanding®   "In¢   roughlù   meanó  "accordinç   tï   commoî 
understanding¬  surrounded¬  contained¬ oò helä bù something"¬ iî 
thió  caså  youò hands®  "On¢ meanó "iî á  locatioî  superioò  tï 
something¬  á  positioî iî whicè somethinç (iî thió caså time© ió 
beneatè it"® Buô what¬ É wondered¬ ió "time"?
     Conveniently¬  therå  ió  á  recenô booë oî thå  subjecô  bù 
Stepheî W®  Hawking¬  "Á Brieæ Historù oæ Timeº Froí thå Biç Banç 
tï Blacë Holes"¬  thaô explainó iô nicely®  Thå onlù waù thaô  wå 
caî  avoiä  conceivinç  oæ thå Biç Banç aó á  singularitù  ió  tï 
regarä  timå aó imaginary®  Thaô is¬  iô ió measureä bù imaginarù 
numbers®  É  diä  noô  aô firsô  understanä  thå  terí  imaginarù 
numbers¬ whicè Stepheî Hawkinç defineó onlù aó "speciaì numberó ® 
®  ®  thaô  givå negativå numberó wheî multiplieä bù themselves"¬ 
buô mù unabridgeä Merriam-Webster'ó IIÉ sayó aî imaginarù  numbeò 
ió  "á compleø numbeò (sucè aó 2+3i© whoså imaginarù parô ió  noô 
zero¢  anä  mù  unabridgeä Randoí Houså sayó  "á  compleø  numbeò 
havinç  itó reaì parô equaì tï zero"¬  sï É guesó wå kno÷ ho÷  tï 
measurå time!
     Measureä bù imaginarù numbers¬ spacå anä timå arå reallù thå 
samå  thing¬  anä  thå  thermodynamiã arro÷ oæ timå  thaô  pointó 
steadilù   towarä   entropy¬    oò   disorganization¬   anä   thå 
psychologicaì   arro÷  oæ  timå  thaô  pointó   steadilù   towarä 
organization¬  and¬  indeed¬ thå cosmiã arro÷ oæ timå thaô pointó 
steadilù towarä expansioî oæ thå universe¬  alì poinô iî thå samå 
direction®  Thió maù bå illustrateä bù salt®  Iæ yoõ poinô á salô 
shakeò  towarä youò kitcheî counteò thå salô wilì spilì ouô iî  á 
disorganizeä fashion®  Iæ yoõ shakå it¬  thå disorganizatioî wilì 
increase®  Buô  iæ  therå  haó  beeî á  loô  oæ  humidity¬  aó  É 
experienceä  durinç  mù recenô triğ tï Hawaié foò  research¬  thå 
disorganizatioî  decreases¬  tï  thå poinô thaô thå  salô  knockó 
abouô  iî thå shakeò anä won'ô disorganizå aô  all®  Sheilá  (whï 
accompanieä me© saiä wå shoulä puô ricå iî it¬  buô É pointeä ouô 
thaô  iô  ió toï latå tï puô ricå iî thoroughlù  organizeä  salt® 
Thaô experiencå leä tï aî insighô that¬ haä Sheilá noô spilleä iô Štï  Brucå Caitling¬  aî aero-spacå engineeò froí Flushinç stayinç 
iî  thå  adjoininç beachsidå cottage¬  whï publisheä  iô  withouô 
acknowledgemenô  oæ itó sourcå iî hió interofficå  newsletter¬  É 
coulä  saù  É  aí impartinç herå foò thå  firsô  time®  Thaô  is¬ 
densitù  ió  proportionaì  tï  organization¬  especiallù  iî  weô 
climates!
     Thå  report¬  whicè consisteä onlù oæ noteó durinç  ouò  twï 
weekó  iî  Hawaii¬  waó  slowlù accumulatinç  undeò  thoså  humiä 
conditionó  aó ne÷ incrementó emergeä anä Sheilá jotteä theí dowî 
oî á paä that¬ É aí sorrù tï say¬ waó badlù staineä bù suntaî anä 
otheò lotions¬  aó wå workeä mainlù oî thå beach® Iô waó becominç 
increasinglù organizeä iî imaginarù timå untiì thå evenô  horizoî 
É  wilì  comå  tï  iî á moment®  Iô ió noô  cleaò  whetheò  evenô 
horizonó  occuò iî imaginarù time¬  buô Brucå haä tï leavå á  fe÷ 
dayó beforå wå werå readù tï return¬ anä hå waó operatinç iî reaì 
time!
     Brucå anä Sheilá were¬  tï saù thå least¬ gettinç organized® 
Likå weô salt® Willamae¬ Bruce'ó wife¬ tooë nï notice¬ aó shå waó 
almosô  continuallù  strunç ouô oî grasshoppers¬  buô  É  haä  mù 
reporô tï thinë of¬ anä Sheila'ó timå waó oæ thå essence¡ Iæ theù 
werå goinç tï havå aî evenô horizon¬  É didn'ô wanô tï geô suckeä 
intï  it¡  Ouò cottageó haä evolveä intï á nï boundarù  conditioî 
witè  thå stronç forcå suspendinç thå uncertaintù principlå whilå 
thå  reporô  waó  undergoinç á reä  shift®  Thió  waó  wherå  thå 
meaningó oæ iî anä oî becamå critical!
     Bruce¬  oî  thå  nighô beforå hå anä Willamaå haä tï  leave¬ 
suggesteä thaô onå oæ us¬ meaninç må becauså hå haä turneä iî hió 
rentaì  caò sincå Sheilá haä promiseä tï geô theí tï thå  airporô 
iî  thå  morninç anä thå threå oæ theí werå toï ploweä  tï  drivå 
anyway¬  thaô onå oæ uó gï intï towî tï picë uğ somå burritoó foò 
dinner®  Willamaå  wanteä  tï comå alonç becauså shå waó  ouô  oæ 
cremå då cacao¬  whicè É coulä havå pickeä up¬  buô shå saiä  shå 
wanteä  thå air®  Energù waó onlù abouô 10° GeV¬  sï  unificatioî 
seemeä unlikely® 
      Willamae¬  iî  whitå chenillå  short-shorts¬  bandeau¬  anä 
rubbeò flip-flops¬ heò bobbeä blondå haiò radiatinç iî á bleacheä 
Afro¬  lolleä  iî  thå  passengeò seaô likå á  Moebiuó  striğ  oæ 
entropy®  Shå  wanteä  tï watcè thå sunset®  Heò lasô  sunseô  oî 
Kuwai¬  shå  said®  Sï É parkeä aô thaô secludeä beacè wherå  seá 
turtleó  sometimeó comå ashorå tï laù theiò eggs®  Iô waó aô  thå 
juncturå oæ thå lighô coneó oæ absolutå pasô anä absolutå future¬ 
thå evenô horizoî surginç witè thå pulsinç golä oæ thå suî easinç 
itó waù towarä Japan¬  thaô onå thinç leä tï another¬ albeiô witè 
morå oæ thå sweetnesó oæ revengå thaî oæ desirå oî mù part¬ anä á 
loô oæ sanä iî between.
     Thå  probleí was¬  Willamaå diä noô wanô tï geô heò haiò  iî 
thå sand®  Shå haä jusô washeä iô thaô afternooî foò thå triğ thå 
nexô daù anä didn'ô wanô tï wasè iô agaiî because¬ shå said¬ thaô 
woulä looë suspicious¬ thougè sï faò aó É waó concerneä Brucå waó 
entitleä tï alì thå suspicioî hå careä tï muster®  Sï aó shå  goô 
ouô  oæ thå caò shå pickeä uğ thå notepaä Sheilá haä lefô oî  thå 
shelæ undeò thå dash® Shå spreaä iô opeî oî thå beacè anä laù heò 
heaä  oî that¬  thougè iô diä preciouó littlå good¬  thå waù  shå 
thrashed®  Iô  waó darë wheî wå wenô oî foò thå burritos¬  anä  É 
forgoô alì abouô thå notepad.Š     Aô anù rate¬ iæ yoõ reallù wanô tï kno÷ whaô thaô versioî oæ 
thå reporô ió iî oò on¬  yoõ woulä havå tï enteò reaì time¬ whicè 
É  woulä  noô advise®  Thå cosmologicaì constanô applieó iî  thaô 
realm¬ á dreadfuì fiction¬ anä Einsteiî waó sorrù hå inventeä it® 
Aó  yoõ  know¬  Goä abhoró (aâ « horre-re© á  nakeä  singularity® 
Blacë holes¬ oò eveî blondå ones¬ arå protecteä froí vie÷ bù weaë 
cosmiã censorship® Eveî Brucå respecteä that¬ thougè Willamaå diä 
havå  tï shampoï agaiî thaô evening¬  buô hå couldn'ô havå  careä 
less¬  havinç beeî drawî ouô likå spaghetté bù thå differencå  iî 
gravitationaì  forcå  oî hió uppeò anä loweò parts®  Anä  Sheila¬ 
well¬  Sheilá neveò noticeä thaô heò notepaä waó missing®  That'ó 
ho÷  committeä  Sheilá is®  É wilì neveò understanä ho÷  shå  goô 
seniority.
     Onå oæ thå meaningó oæ "on¢ ió about®  Thå report¬  replaceä 
bù thió memo¬  ió oî timå iî thió sense¬  anä iæ yoõ arå  readinç 
it¬ É maù assumå iô ió no÷ in® É hopå thaô answeró youò question® 
                                        Respectfully,
                                        Youò Whitå Dwarf
