Date: Tuesday, 23 February 1988  08:13-PST
From: Doug Braun
Re:   Z-280 documentation

Several people mailed me asking for info about the Z-280 chip.
Here is some information:

 I got two at a place called Western Micro (a distributor) in
 Campbell, CA.  The were about $45 each.

 What you really need is the documentation.

 You need to order it from the factory.  The sales offices are usless
 for serious information.

 You want:  

 Z280 MPU Preliminary Product Specification	00-2259-05	N/C
 Z280 Technical Manual				03-8224-02	$15.00

 Send a check for the above amount, plus 10% for S/H, to:

 Zilog
 M/S C1-0
 210 Hacienda Ave.
 Campbell, CA 95008-6609

 or call:  408 370-5987


Doug Braun				Intel Corp CAD
					408 496-5939

 / decwrl \
 | hplabs |
-| oliveb |- !intelca!mipos3!cadev4!dbraun
 | amd    |
 \ qantel /
