.RR--!----!----!----!----!----!----!----!---R
.po2
.pl50
.oj
.ulon
TÏ BOLDLÙ GO...
bù Jií Taylor

Iî  aî efforô tï expanä thå horizonó oæ  thió 
humblå periodical¬ ouò Mosô Honorablå  Editoò 
haó inviteä må tï enlargå thå rangå oæ topicó 
upoî whicè tï expound.

Iî  otheò words¬ Leå sayó it'ó OË foò  må  tï 
writå  abouô somethinç otheò  thaî  computeró 
anä CP/M® Whew¡ Thaô doeó makå lifå á  littlå 
easier® É mean¬ ho÷ manù differenô wayó caî á 
persoî  saù thaô CP/Í ió betteò  thaî  MÓ-DOÓ 
AND‚ bå funnù abouô iô aô thå samå time® Thoså 
whï  believå wilì continuå tï believe¬  thoså 
whï don'ô-well¬ wå don'ô neeä 'eí anyway.

Likå mosô oæ you¬ É don'ô livå iî fronô oæ mù 
CRT®   Althougè   iô  doeó  seeí   thaô   waù 
sometimes® So¬ iî celebrátioî oæ thå resô  oæ 
ouò  lives¬ oveò thå nexô couplå  oæ  issues¬ 
I'lì bå writinç ne÷ articleó oî á varietù  oæ 
topics® 

Thå  gloveó arå off¬ thå gauntleô  ió  throwî 
anä  maybå  no÷  É  won'ô  diå  oæ   creativå 
boredom.

What'ó  coming¿  Bubblinç awaù  oî  thå  bacë 
burneró aó wå speaë arå articleó abouô livinç 
iî  thå  future¬ whù writeró  writå  anä  ho÷ 
computeró  caî  drivå yoõ crazy®  See¬  therå 
wilì stilì bå gooä stufæ foò thå puristó  whï 
thinë thaô nothinç buô computeró shoulä bå iî 
á  computeò  magazinå (althougè  nobodù  eveò 
accuseä må oæ beinç purå abouô anything©  anä 
otheò  stufæ foò thoså oæ uó whï livå iî  thå 
reaì world.
ŠIt'ó  alsï beeî suggesteä thaô É writå  abouô 
photoçraphy¬  ne÷ tecènologies¬ politicó  anä 
otheò  subjectó toï numerouó  (anä  sometimeó 
toï weird© tï mention.

Á fe÷ oæ theså pieceó wilì bå seriouó (oò  aô 
leasô aó seriouó aó É eveò get© anä somå wilì 
bå funny® Yoõ geô tï decidå whicè ió which.

[Audiencå paòticipátioî part¬ takå one:]

Therå arå twï wayó É caî gï abouô doinç this® 

     (1© É caî jusô writå whateveò amuseó  må 
     oò 

     (2©  yoõ caî droğ må á postcarä  aô  thå 
     addresó  belo÷ anä leô må kno÷ whaô  yoõ 
     thinë oò whaô yoõ wanô tï read.

Dï  yoõ wanô morå iî-deptè lookó aô  thå  waù 
technologù  anä  thå mediá  arå  shapinç  ouò 
lives¿  Dï yoõ wanô funnù stuff¿ Maybå  you'ä 
likå tï reaä aî intervie÷ witè youò  favoritå 
SysOp?

Yoõ telì me® Joiî må oî thió literarù  voyagå 
tï boldlù gï wherå nï onå haó gonå before.

Otherwise¬ må anä 'dá boys'lì jusô haftá takå 
youú oî á littlå ridå oæ ouò own.

-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-½-
JIÍ  TAYLOÒ ió á deranged¬ paranoiä  essayisô 
whï  writeó  abouô  computers¬   photoçraphy¬ 
moneù anä whateveò suitó him® 

Attentioî    Publishersº    reprinô    rightó 
availablå  aô reasonablå rates¬  easù  crediô Šterms®  Contactº  Jií  Taylor¬  PÏ  Boø  642¬ 
Newington¬ CÔ 06111.

Copyrighô 199° Jameó F® Taylor
Alì rightó reserved
.paŠ