
                               Meeting Notes
                             By Gary Stagliano
                            Secretary Ex Officio

                                August 1992

Brought in For our Horror by Stephen Griswold and Lee Bradley:

A CompuPro System 8/16 Multiuser system with formatted 37MB drive but the 
system tracks etc were formatted. It consists of a 286 running at 8Mhz, 
CP/M-86 with 3MB of memory. The original cost was $12,000 when released. It 
has a S100 Bus with 1MB static (Can the YASBEC use this?) RAM.  
Unfortunately, the hard drive was reformatted, making the system of little 
value. The monitor failed to work during the demonstration. Perhaps the 
lighting had something to do with this?

Secretary/Treas Report:
$18.00 for newsletters. $632.00 remaining

MYZ80, by Simeon Cran: 

MYZ80 is a Z80/64180 emulator package. It emulates Z80 and CP/M 2.2 and 
CP/M PLUS for AT class and better IBM compatibles. MYZ80 provides an 
interface (the MYZ80 API) to the host computer which allows real Z80 BDOS's 
to run in the MYZ80 environment. This interface provides disk and character 
I/O as well as two banks of 64k RAM (with common area) and a large RAM 
disk. These unique features allow MYZ80 to run 'real' CP/M 2.2, CP/M 3.0, 
Z-System and ZPM3.

Swap Meet:

A CCP/M-sponsored swap meet was proposed by Gary J. Stagliano. It was 
suggested that we have one in conjunction with a Z-Fest. It was also 
suggested that we wait and go to Trenton in April.

Nominating committee: Al Hathway, Tom Manion, Gary J. Stagliano

Tentative Slate:

President: Al Hathway
Program Planner: Open
Treasure: Tom Mannion
Secretary: Gary J. Stagliano

non-elected: Newsletter: Tom Veile

For Sale or Trade:

Xerox 860 Available (Desktop Publishing system?) floor model tower, wide 
carriage daisy wheel printer. Call: 393-3470 in Woodbridge, Ct. 8/11/92 
huge docs. Works. Will swap for ms-dos hardware.

General Discussion:

There was a general discussion on the state of the club, computing and 
pizza. The consensus was that CCP/M is a computing club first. While we 
emphasize CP/M and Z-System, we are also interested in other computers and 
hardware. We are Hackers in the true (good) sense of the word. The club 
will continue as long as there is interest in computing, hardware, firmware 
and software. The advent of advanced CP/M simulators for IBM and other 
computers will mean that CP/M will survive well beyond the demise of the 
last Kaypro.

Demo of the Month:

Steve Dresser demonstrated the Language Master 6000 SE, proving that 
Smaller is Better! It has a talking dictionary, a thesaurus and 
definitions. It runs on a V20 at a moderate speed. At a $500.00 price for 
this special edition, it seems to have a lot of power but the speech 
synthesis is not all that clear.

Attendance:

Al Hathway, Tom Veile, Tom Mannion, Gary J. Stagliano, Lee Bradley, Steve 
Dresser, Linda Bradley, Stephen Griswold.

 