
                     CCP/M Z-PLAN ORDER FORM

Send this form along with your check made out to Lee Bradley to
CCP/M Z-Plan Contact: Lee Bradley, 24 East Cedar Street,
Newington, CT 06111.  You must be a member of CCP/M to order thru 
us.

Your Name:    __________________________________________________

Your Address: __________________________________________________

              ____________________________ , _____   ___________

Your Telephone Number (home and/or work w/ area code):

              ( ____ ) ______   ________________________________

Your computer __________________________________________________

Your disk format (size, density/tracks, sides:)

              __________________________________________________

Product                                  

 1.  NZ-COM (CP/M-2.2) $55.95   2.  Z3PLUS (CP/M-Plus) $55.95
 3.  ZCPR34 Source $39.95       4.  NZ-COM w/ Z34 Source $79.95
 5.  ZSDOS/ZDDOS $56.OO         6.  BackGrounder-ii $60.00
 7.  DateStamper $40.00         8.  JetFind $40.00

 9.  DosDisk $24.00 (for XBIOS $28.00, kit $36.00)
10.  BDS C for CP/M (and for ZCPR3, Too!) New!!!  $72.00

Product(s) desired: ___________________________________________
      
                    ___________________________________________

Subtotal Price:     ___________________________________________

If you live in MA, 5% Sales Tax _______________________________

Shipping/Handling                        $3.00

Enclose your check made out to Lee Bradley for the total amount.

