
Date: Friday, 30 March 1984  10:50-MST
From: Bob Bloom
To:   All
Re:   WordStar Message Patch (faster entry to WS)

For WordStar Version 3.3 (n/a to 3.0)

Make the the follwing byte changes via ddt in the installed WS.COM
	at 3f3d from 20 to 00
	at 410f from CD to 00
	at 2b2 from 40 to 00

the above changes to opening logos and copyright notice

to make it run generally faster the following are also helpful:
	at 2af from 3 to 2
	at 2b0 from 9 to 4
	at 2b1 from 19 to 8
	at 2b3 from 9 to 5

bob bloom (the above patches are NOT exactly the same as the ones I
posted earlier - I've learned some more since then)
