WSP33 .LBR   Wordstar 3.3 Patches by  Mark S. Stein  11/4/84

The files contained herein comprise WSP33.ASM, WSP33.HEX, WSP33-A.SUB,
WSP33-B.SUB, WSP33.DOC and EX14.COM. In order to implement the
patches, the additional files needed include DDT.COM, ASM.COM and a
newly-installed version of Wordstar which must be renamed WSINSTAL.COM.

The following is a summary of the patch effects that are used in
conjunction with WORDSTAR version 3.3 for the Osborne I. Minor
modifications to the companion source file WSP33.ASM can be made 
to accommodate other computers and printers.

1) One set of patches within WSP33.ASM is used to set up the 
   Osborne I Arrow keys to allow the automatic switchover 
   from/to  CP/M  to/from  Wordstar. 

2) The other patches within WSP33.ASM are used to provide 
   specific program and printer patches and the default
   values for the left and right margins have been preset
   to columns 1 and 80, respectively. Modify all the default
   values to the desired value or toggle state prior to
   assembling with ASM.COM.

3) The MicroPro LOGO and legal jargon have been eliminated 
   and screen blanking occurs upon entering as well as 
   exiting Wordstar. The underlining effect has also been 
   eliminated. If the dimming effect is NOT desired, 
   change the value of 29H at location 0269H to 28H using 
   EDFILE or simply change the "29" appearing on the line 
   below S269 to a "28" (see patching routine within either
   WSP33-A.SUB or WSP33-B.SUB).  

4) The AUTOLOG onto "B" feature is employed within WSP33-B.
   SUB and becomes automatically installed. If this feature
   is not desired, use WSP33-A.SUB instead of WSP33-B.SUB.
