Date: Wednesday, 10 April 1985
From: Werner Uhrig
Re:   a point of Canadian law. importing software into Canada.

        QUIRKS OF CANADIAN CUSTOM-DUTIES ON COMPUTER SOFTWARE

According to a letter in REMARK of April 1985, page 7, Canadian
customs distinguish between "applications" and "operating systems"
software. I quote:

Canada Customs divides software into the categories of operating
system software and applications software.  OS software is considered
to be an integral part of the computer and is, therefore, considered
as hardware, which attracts both duty and federal sales tax.  This
duty and sales tax is paid on the TOTAL PURCHASE PRICE of the
software.

NO DUTY is paid on applications software.  Federal sales tax is
payable, but ONLY on the value of the physical medium on which the
program is recorded.

Of course, to take advantage of this distinction, you must provide
sufficient information on the shipping invoice, and probably bring the
Canada Custom officer's attention to his department's policy in this
regard, which is set out in Revenue Canada Memorandum D13-11-2.

[An example of] what the invoice should also say is applications
software, recorded on 5-1/4" diskette magnetic medium, the medium
itself having a value of $X".

The practical effect of this, of course, is that the recipient pays
10% of next to nothing, and that customs might not even bother to
collect the few cents.

The same applies to software recorded on a ROM-chip.  Incidentally,
disk drives, power supplies and cabinets, imported into Canada by
themselves, and not as part of a computer, attract federal sales tax,
but NOT duty, which is generally 3.9% for computer equipment that is
subject to duty.

Direct any questions and request to the Minister of Revenue Canada,

    The Honourable Perrin Beatty,
    Minister, Revenue Canada - Customs and Excise
    Connaught Building, McKenzie Avenue
    Ottawa, Ontario, K1A OL5

[any thanks for bringing this useful information to our attention goes to:

    Jim Shantora,
    Barrister, Solicitor, Notary Public, 
    109 Silversted Drive
    Agincourt, Ontario M1S 3G4

Note also, that REMARK is the Official Magazine for users of
Heath/Zenith computer equipment and your local HUG - Heath Users Group
- or Zenith-dealer should have a copy for review.  --- Werner ]
