
Msg #5647 posted 01/30/87  by Micromint  
To: ALL USERS     About: SB180 9.216 MHz (38 lines)


                    ATTENTION ALL SB180 OWNERS !!!!!

                      9.216 MHZ SPEED UPGRADE !!!


It pains us a lot to admit this, but WE WERE WRONG!  For months we've
been saying that the SB180 would only be available in 6.144 MHz because
we were explicitly told by Hitachi that higher speed HD64180 chips
would only be available in PLCC packages.  The inscrutable Japanese have
changed their minds and are now producing and delivering 8 MHz 64180
chips in shrink DIP packages.  These are very conservative specs and the
new chips easily run at 9.216 MHz.

For SB180 owners this is a bonus.  It now means that you can upgrade the
speed of your SB180 by 50%!  Depending on the application, tests show
that a 9 MHz SB180 can actually run faster than an IBM PC/AT.

  
Upgrading your SB180 from 6.144 MHz to 9.216 MHz can be easily done if
you can unsolder a crystal and replace it with a new one.  The rest of
the change merely involves unplugging and replacing the monitor EPROM,
switching a few LSTTL chips and the processor with faster equivalents,
and updating some processor speed dependent programs in your operating
system.

The 9 MHz Upgrade Kit includes a new crystal, 8 MHz HD64180, monitor
         EPROM, three high speed "S" TTL chips, software diskette, and
         instructions.
                        order SB180-9UPG ..................... $79.00 
                                                          (ppd in USA)

Order your SB180-9UPG from:
                        Micromint Inc.
                        4 Park St.
                        Vernon, CT 06066

orders: (800) 635-3355    Information: (203) 871-6170    Telex: 643331

