Date: Sunday, 12 August 1984
From: Eric Stork
To:   All CP/M users
Re:   The Programmer's Guide to CP/M

This message is of interest to owners (and prospective owners) of
Andy   Johnson-Laird's  superb  THE  PROGRAMMER'S  CP/M  HANDBOOK
(Osborne/McGraw-Hill), and is based on recent correspondence from
the author.

In the original edition, about two  pages  of  listing  were  not
printed.  The missing listing is lines 04628 thru 04919 (see page
261-262).   Anyone  who wants the missing lines can get them from
the author's office: Johnson-Laird, Inc., 6441 SW  Canyon  Court,
Portland  OR  97221.   Send  a SASE with a note on what you want.
(Johnson-Laird said the  book  went  into  its  2nd  printing  in
January  1984,  and  the  missing  material should be in that 2nd
version.  But he is out of the country on a project and tells  me
he has not seen the 2nd version.)

Other errors in the book:

    .  page 64, figure 4-3, location 0153, correct to read:
               JM   CTPX     (instead of MB  CTPX)

    .  On page 149, 7 lines from the bottom, there is a reference
       to  CCP+6.   That  reference  should be CCP+0.  The letter
       from  the  author  said  that  there  may  be  other  such
       erroneous  references,  for  CCP+6 is a CP/M-86 convention
       and thus the source of the error, but  he  has  not  found
       other such errors.

    .  page 258, line 03828, change this line to read:
               STA  MOB$Character

    .  page 282, after line 09270, insert:
               LXI  H,Disk$Control$5
       (Note:  after inserting that line the byte references will
       be offset by 3 bytes, if you type it all in  and  assemble
       it.)

Finally, Johnson-Laird wants to know about any other bugs, typos,
errors and what have you that anyone may spot.  You may send such
information DIRECT to me and I'll relay to Johnson-Laird.

If you have not yet seen the book, look at it.  If  you  buy  it,
you'll  probably  not  lend  it  out  --  it's too valuable to do
without for anyone who has any notion about playing  around  with
8080 assembler and CP/M in general.

Eric Stork

[Note:  Messages for Eric may be left on RCPM Royal Oak (313-759-6569)
and I will make sure they are relayed.  -- Keith Petersen, W8SDZ]
