Date: Wednesday, 6 June 1984
From: hplabs!hao!seismo!cmcl2!floyd!clyde!burl!ulysses!gamma!mb2c!uofm-cv!tom
To:   All
Re:   Prom Erasure

There are two different kinds of ultraviolet tubes available--short
wave and long wave.  The kind used to illuminate posters, etc. are
long wave.  The kind used to erase EPROMS are short wave.  Short wave
UV is the component of sunlight which causes tanning (and sunburn, and
skin cancer), so you have to be very careful not to look at a short
wave UV lamp.  I've been using a General Electric G8T5 8-watt
germicidal tube with very good results.  If you want to build an
eraser from scratch then you'll also need an 8-watt ballast and an
FS-5 starter.  There are some back issues of BYTE magazine which
describe the construction of an EPROM eraser.  However, at least one
of these articles INCORRECTLY suggests using a long-wave UV lamp.  The
easiest way (and probably cheapest way) to build an EPROM eraser is to
buy the G8T5 tube and put it in an inexpensive fluorescent desk lamp
which already contains the correct ballast, starter, sockets, cord and
power switch.

Good luck and have fun.  Let me know if you need more information.

				Tom Libert
				Dept. of EECS
				Division of Computer Sci. and Engin.
				Univ. of Michigan
				Ann Arbor, MI 48109
				(313) 763-6474
