
     ADDHD     45   |    ANDHD     48

     BBLINE    31   |    BIOS      67
     BDOS      67   |    BLINE     31


     CAPS      68   |    COMPB     40   |    CRC1K     51
     CAPSTR    68   |    COMPBC    40   |    CRC1UPD   50
     CATH      69   |    COMPHD    40   |    CRCCLR    50
     CCOUT     44   |    CONDIN    42   |    CRCDONE   50
     CIN       43   |    COUT      43   |    CRCK      51
     CLOUT     44   |    CPOUT     44   |    CRCUPD    50
     CMPH      46   |    CRC1CLR   50   |    CRLF      42
     CODEND    69   |    CRC1DONE  50   |    CST       43

     DBUFFER    8   |    DIRFS      7   |    DIRSEL    12
     DFREE      9   |    DIRLOAD   11   |    DIRSLOAD  11
     DIRALPHA  12   |    DIRNPACK  14   |    DIVHD     46
     DIRF       7   |    DIRPACK   13   |    DPARAMS    9

     EN        69   |    EVAL16    16
     EVAL      15   |    EVAL2     17
     EVAL10    16   |    EVAL8     17

     F$CLOSE   24   |    F$OPEN    23
     F$DELETE  25   |    F$READ    27
     F$EXIST   26   |    F$RENAME  26
     F$MAKE    25   |    F$WRITE   27
     F$MOPEN   24

     Fn$GET    21   |    FILLBC    70
     Fn$PUT    21   |    FNAME     28
     FIn$CLOSE 20   |    FOn$CLOSE 20
     FIn$OPEN  19   |    FOn$OPEN  20
     FILLB     70   |    FSIZE     10

     GETUD     55

     HFILB     70   |    HMOVB     71
     HFILBC    70   |    HMOVBC    71

     INITFCB   29   |    INSTR     41
     INLINE    32

     LA2HC     37   |    LHLDC     36
     LA3DC     38   |    LOGUD     55
     LADC      38   |    LOUT      43
     LCRLF     42   |    LPRINT    34
     LHL4HC    35   |    LPSTR     34
     LHL5DC    36



Š
     MA2HC     37   |    MHLDC     37
     MA3DC     38   |    MOVEB     71
     MADC      39   |    MOVEBC    71
     MHL4HC    35   |    MULHD     46
     MHL5DC    36

     NEGH      46

     ORHD      48

     PA2HC     37   |    PHLDC     36
     PA3DC     38   |    POUT      43
     PADC      38   |    PRINT     34
     PAUSE     71   |    PSTR      34
     PHL4HC    35   |    PUTUD     54
     PHL5DC    36

     RETUD     55   |    RND       53
     RIN       43   |    RNDINIT   52
     ROTLH     47   |    RNDSEED   52
     ROTRH     47

     SCANNER   40   |    SORT      57
     SHFTLH    47   |    SSBINIT   57
     SHFTRH    48   |    SUBHD     45

     XORHD     48

     ZCPRQ     60   |    ZFSTAT    62
     ZCPRSET   59   |    ZINIEXT   59
     ZDNFIND   64   |    ZINIMC    58
     ZFNAME    65   |    ZMCPTR    61
     ZFNINIT   64   |    ZPFIND    61

