-------
Message #10241  ** General **
Posted: 03/04/87 at 12:06 pm
  From: David McCord
    To: Alan Gerace
 About: T3master error codes (14 lines) 

That's correct.  The T3MASTER/T3SERVER error codes do not appear in
the documentation.  However, they are:
 
01 = Ambiguous file name not allowed
02 = Directory not found
03 = file exists and should not
04 = file create failed
05 = file not found
06 = file write error
07 = file name not provided
08 = TPA overflow error
09 = user needs wheel privileges
 
...Dave

