

Date:     12 October 1984

To:       All SYSOPs and Users of ZCPR3

From:     Echelon, Inc. 

Subject:  Domain Status of ZCPR3 and
          Application Programs

It's  been  brought to our attention that there may be  confusion 
relative  to the status of the programs known as DISCAT  and  Z3-
DOT-COM.   We  have  heard of these files being put up  on  RCP/M 
systems.   Such action is illegal!

We wish to make clear the meaning of public domain,  copyrighted, 
and limited distribution programs.

ZCPR3   and  the  utilities  are  released  for  private  use  by 
individuals  in  a non-commercial environment.   This  is  called 
limited  or restricted  distribution.   You cannot sell ZCPR3  or 
any  of  its  utilities without first obtaining  a  license  from 
Echelon.   They  are  copyrighted  and  the  copyright  has  been 
assigned to Echelon by Richard Conn.   The owner of the copyright 
determines   the   domain  status  of  a  program   by   whatever 
restrictions he places on it.

The legal definition of "public domain" is:   you may do anything 
you wish,  sell,  give away,  modify,  etc.   ZCPR3 is not in the 
public domain; you cannot sell it without a license.

Presently two programs (with more to come) are not to be released 
to the RCP/M network,  are under strict license:   DISCAT and Z3-
DOT-COM.  These programs may be purchased only from Echelon, Inc.  
The COM files are named:   CATCHECK,  CATERASE, CATFREE, CATMAKE, 
CATMERGE, CATNAME, CATRMDSK, CATSCAN, CATUPD, Z3L and the special 
files  are  ENV.SPR,   SYSFCP.SPR,   Z3BIO.SPR,   Z3CPR.SPR,  and 
Z3MOV.BIN.   These  will  never  be released to SIG/M  or  public 
message  networks.   These  are programs to keep  Echelon  alive, 
making money,  with some of that money going to Richard Conn  and 
Joe Wright.

Please guard our rights...if we don't stay in business there will 
be no more ZCPR3's or enhancements or applications taking special 
advantage  of the system capability.   We are practically  giving 
the  software away now,  not making much off each package.   Come 
and  join in our support of the 8-bit CP/M world that  many  have 
been so quick to abandon.  Thank you.
