

                  Sig/M Report - December 1981
                           by Hank Kee

AfteÚ† onÂ† yeaÚ oÊ operation¨† thÂ Sig/Õ UseÚ Grou Librar˘† no˜ ç
containÛ 47 volumesÆ ThiÛ haÛ beeÓ madÂ possiblÂ b˘ thÂ unselfisË ç
effortÛ† oÊ man˘ whÔ havÂ volunteere‰† theiÚ† servicesÆ†  Equall˘ ç
importanÙ† arÂ alÏ thosÂ whÔ havÂ contribute‰ materialÛ intÔ† thÂ ç
library. 

WÂ† havÂ† beeÓ informe‰ thaÙ beginninÁ witË CPMU« volumÂ† 55¨† iÙ ç
wilÏ† contaiÓ† thÂ Sig/Õ UseÚ Grou Librar˘ startinÁ† witË† Sig/Õ ç
volumÂ† 1Æ† ThÂ director˘ oÊ CPMU« volumeÛ 5µ througË 6¥ wilÏ† bÂ ç
publishe‰ iÓ LifeLinesÆ† IÙ iÛ ouÚ understandinÁ thaÙ thÂ volumeÛ ç
wilÏ† remaiÓ† intacÙ althougË thÂ CP/Õ UserÛ† Grou† (CPMUG©† haÛ ç
altere‰† thÂ† Sig/Õ† cataloÁ designationÛ internall˘ aÛ† welÏ† aÛ ç
externallyÆ† The˘† havÂ opte‰ tÔ refeÚ tÔ thesÂ volumeÛ aÛ† CPMU« ç
volumesÆ† WÂ† hopÂ thÂ unilateraÏ actioÓ oÊ thÂ CP/Õ UserÛ† Grou ç
wilÏ noÙ deteÚ contributorÛ froÌ continuinÁ tÔ submiÙ programÛ oÊ ç
generaÏ interesÙ intÔ thÂ Sig/Õ LibraryÆ  

Recent Sig/M Releases:

Sig/M	Volume 43	8080 TINCMP Compiler and
			Pidgin Programming System
			CP/M-86 Bios Support

		-CATALOG.043	contents of Sig/M volume 43
				released November 25, 1981
		ABSTRACT.043	abstract of Sig/M volume 43
		ACKLIST.043	acknowledgement file
		CRCKLIST.043	checksum of Sig/M volume 43

index	name		size	description		

43.01	DESCRIP .DOC	16K	details of TINCMP and PIDGIN
43.02	IOCMPLX .ASM	19K	PIDGIN programming system
43.03	IOCMPLX .REL	 2K	     /
43.04	MACROS  .PGN	 8K	    /
43.05	PIDGIN  .S2M	10K	   /
43.06	PIDGINLB.REL	 1K	  /	
43.07	PIDMATH .ASM	 5K	 /
43.08	PIDMATH .REL	 1K	/
43.09	STAGE2  .COM	12K	STAGE2 support system
43.10	SYSTEM  .ASM	 1K	PIDGIN programming
43.11	SYSTEM  .REL	 1K	/
43.12	TINCMP  .COM	17K	TINCMP compiler
43.13	TINCMP  .MAC	20K	        /
43.14	TINCMP  .PGN	12K	       /
43.15	TINCMP  .REL	 5K	      /
43.16	TINTEST1.PGN	 3K	     /	
43.17	TINTEST2.PGN	 3K	    /
43.18	TINTEST3.PGN	 1K	   /
43.19	TINTEST4.PGN	 3K	  /ä43.20	TINTEST5.PGN	 2K	 /	
43.21	TINTEST6.PGN	 2K	/
43.22	WC      .PGN	 2K	TINCMP test program
43.23	WRNXT   .ASM	 1K	PIDGIN console I/O
43.24	WRNXT   .REL	 1K	/
43.25	CBIOS	.A86	17K	CP/M-86 Bios
43.26	GOCPM86	.ASM	 1K	 /
43.27	ERQ	.A86	 3K	/
43.28	SD	.A86	15K	CP/M-86 directory sort

Copyright (C) 1981 by Sig/M-Amateur Computer Group 
of New Jersey Inc., Box 97, Iselin NJ 08830-0097

Sig/M	Volume 44	Miscellaneous CP/M Utilities

		-CATALOG.044	contents of Sig/M volume 44
				released November 25, 1981
		ACKLIST.044	acknowledgement file
		CRCKLIST.044	checksum of Sig/M volume 44

index	 name		size	description

44.01	 CHAT16  .ASM	 8K	interactive remote/local operations		
44.02	 CPM2HELI.DOC	 4K	CP/M to Helios
44.03	 CPM2HELI.OBJ	 1K	 /
44.04	 CPM2HELI.S  	 5K	/
44.05	 DU-V77  .ASM	42K	updated disk utility
44.06	 DU-V77  .DOC	 6K	 /
44.07	 DU-V77  .OBJ	 6K	/
44.08	 FLAGS   .DOC	 2K	edit file attributes
44.09	 FLAGS12 .ASM	12K	/
44.10	 FMAP4   .ASM	11K	update FMAP of cataloging system
44.11	 FMAP4   .OBJ	 2K	/
44.12	 HELI2CPM.OBJ	 1K	Helios to CP/M
44.13	 HELI2CPM.S  	 5K	/
44.14	 PIPPATCH.ASM	 5K	patch for PIP
44.15	 SD-41   .ASM	46K	updated Super Directory
44.16	 SD-41   .DOC	12K	/
44.17	 UNERA   .HLP	 3K	UNERAse erased programs
44.18	 UNERA11 .ASM	 6K	/
44.19	 WASH-10 .DOC	16K	disk directory maintenance utility
44.20	 WASH-16 .ASM	34K	/


Copyright (C) 1981 by Sig/M-Amateur Computer Group
of New Jersey Inc., Box 97, Iselin N.J. 08830-0097

Sig/M	Volume 45	Dungeon - volume 1 of 3
			original code for PDP-11
			
		-CATALOG.045	contents of Sig/M volume 45
				released November 25, 1981
		CRCKLIST.045	checksum of Sig/M volume 45

index	name		size	descriptionä
45.01	ACTORS  .FTN	16K	original code for Dungeon	
45.02	CLOCKR  .FTN	17K		      /	
45.03	DEMONS  .FTN	19K		     /
45.04	DGAME   .FTN	10K		    /
45.05	DINIT   .FTN	12K		   /
45.06	DMAIN   .FTN	13K		  /
45.07	DSUB    .FTN	18K		 /
45.08	DUNGEO  .DOC	22K		/
45.09	DVERB1  .FTN	13K	       /	
45.10	DVERB2  .FTN	18K	      /	
45.11	GDT     .FTN	15K	     /
45.12	OBJCTS  .FTN	21K	    /
45.13	RRND    .MAC	 2K	   /
45.14	RSXTIM  .MAC	 1K	  /
45.15	SVERBS  .FTN	18K	 /
45.16	VERBS   .FTN	21K	/

Copyright 1981 (C) by Sig/M-Amateur Computer Group
of New Jersey Inc., Box 97, Iselin NJ, 08830-0097

Sig/M	Volume 46	Dungeon - volume 2 of 3
			original code for PDP-11

		-CATALOG.046	contents of Sig/M volume 46
				released November 25, 1981
		CRCKLIST.046	checksum of Sig/M volume 46

index	name		size	description

46.01	D       .ODL	 1K	original code for Dungeon
46.02	DTEXT   .DAT   221K	        /
46.03	LIGHTP  .FOR	 6K	       /
46.04	RSTSCB  .CTL	 2K	      /
46.05	RSXBLD  .CMD	 1K	     /
46.06	RSXCMP  .CMD	 1K	    /
46.07	RTBLD   .COM	 1K	   /
46.08	RTCMP   .COM	 1K	  /
46.09	VMSBLD  .COM	 1K	 /
46.10	VMSCMP  .COM	 2K	/		

Copyright 1981 (C) by Sig/M-Amateur Computer Group
of New Jersey Inc., Box 97, Iselin NJ 08830-0097

Sig/M	Volume 47	Dungeon - volume 3 0f 3
			original code for PDP-11

		-CATALOG.047	contents of Sig/M volume 47
				released November 25, 1981
		CRCKLIST.047	checksum of Sig/M volume 47

index	name		size	description

47.01	BALLOP  .FOR	 7K	original code for Dungeon
47.02	DINDX   .DAT	49K			  /ä47.03	DSO1    .FOR	 6K			 /
47.04	DSO2    .FOR	 8K		        /
47.05	DSO3    .FOR	 4K		       /
47.06	DSO4    .FOR	 7K		      /
47.07	DSO5    .FOR	 5K	             /
47.08	DSO6    .FOR	 6K	            /
47.09	DSO7    .FOR	 7K	           /
47.10	NOBJS   .FOR	20K	          /
47.11	NP      .FOR	 5K	         /
47.12	NP1     .FOR	25K	        /
47.13	NP2     .FOR	 6K	       /
47.14	NP3     .FOR	10K	      /
47.15	NROOMS  .FOR	15K	     /
47.16	ROOMS   .FOR	18K	    /
47.17	RTTIM   .FOR	 1K	   /
47.18	SOBJS   .FOR	18K	  /
47.19	VILLNS  .FOR	19K	 /
47.20	VMSTIM  .FOR	 1K	/

Copyright 1981 (C) by Sig/M-Amateur Computer Group
of New Jersey Inc., Box 97, Iselin NJ 08830-0097

Sig/M	Volume 48	Communication Utilities
			Miscellaneous CP/M Support 

		-CATALOG.048	contents of Sig/M volume 48
				released November 25, 1981
		ACKLIST.048	acknowledgement file
		CRCKLIST.048	checksum of Sig/M volume 48

index	name		size	description

48.01	CARRY12 .ASM	 6K	pause prior to load of .COM files	
48.02	MODEM7  .DOC	16K	update of Modem7 program
48.03	MODEM7  .LIB	14K	   /
48.0¥	MODEM∑  .SE‘	 3À	  / 
48.05	MODEM73 .ASM	63K	 /      
48.06	MODEM73 .OBJ	10K	/	      
48.07	SENDOUT3.ASM	 5K	sendout utility for PMMI
48.08	UNSPOOL .ASM	13K	DESPOOL look-alike
48.09	UNSPOOL .DOC	 8K	/
48.10	USRDFLT2.CCP	15K	pseudo CCP User
48.11	USRPW34 .ASM	17K	password for User access control
48.12	XMODEM46.ASM	39K	remote CP/M file transfer program
48.13	SQ      .COM	14K	pack ASCII file
48.14	USQ     .COM	10K	unpack ASCII file

Copyright (C) 1981 by Sig/M-Amateur Computer Group
of New Jersey Inc., Box 97, Iselin NJ 08830-0097
