
Date: Thu, 15 Mar 84 20:54 PST
From: Mike Webb
To:   net.micro.cpm
Re:   MDM7xx hidden feature

I just discovered a feature of MDM7xx which has not been documented (as
far as I know). The feature which allows two alternate dialing services
(ie SPRINT or MCI) can also be used to provide a credit card number when
needed.

MDM7xx documents show that, after defining the alternate dialing sequence
in your overlay (or patch w/DDT) to use the alternate dialing, you simply
put a "<" or ">" in front of the number you wish to call (either direct
type-in or from the "CAL X" menu).  If the alternate number is instead
an appropriate number of wait characters (my Password modem uses ","),
followed by your credit card number, the following works quite nicely:

        CAL 0123-456-7899<
            !            !
            !            +->Inserts the waits + your credit card #
            !
            +-->Tell Ma Bell to ask for your credit card.

I has to experiment with the number of waits and found that 3
seems to work all of the time (2 worked most of the time). Hope this
is "new" info and not just me "discovering" something already generally
known, but I thought it worth the time.

                        Mike Webb
