Date: Sunday, 29 July 1984
From: Eric Stork
To:   Keith Petersen
Re:   MDM7 overlay for Kaypro allows 4800 baud

I  have  modified M7KP-2.ASM in several ways that serve my needs.
Others may have similar needs, and  may  find  the  revised  file
(M7KP-X48.ASM) useful.

The  primary  purpose of the mod is to facilitate the direct 4800
baud (i.e., RS-232 to RS-232, without phone  lines)  transfer  of
files  to and from KAYPROs.  I find that very useful -- I do some
work on the Kaypro, or my  subcontractors  do,  and  then  I  can
upload to my S-100 and continue to process the data into a single
report.

This  can easily be done with three wires.  I explain in the file
how to do it, including a diagram for a simple cross-over  switch
to  match  the other computer's RS-232 configuration (I installed
such a switch into the RS-232 connector itself).

But most importantly, the file is set up so that by saying YES or
NO to two equates, one can also  assemble  it  for  normal  modem
operation,  and one can set it up to run off the KP-n-84's serial
PRINTER port.  That is useful if you do not want to  unplug  your
regular modem whenever you want to transfer a file direct at 4800
baud.

Eric Stork
