
			MODM700.MSG
			Nov. 4, 1984


	NOTE:	This program when assembled is 73 sectors
		long.  Use this figure when merging the
		appropriate overlay file for your computer
		via DDT, etc.  (Most of the overlays were
		written when MDM7xx.COM was only 66 sectors
		and the example included in each says to
		store 66 sectors.)  For MODM700 use:

			B>SAVE 73 MODM700.COM

	NOTE:	Use M7FNK.COM to easily and quickly change
		any of the 10 function key assignments.  You
		can read the M7FNK.DOC file for additional
		information.  (by Sigi Kluger.)  The log-on
		key (CTL-L can be changed in the overlay.

	NOTE:	M7LIB.COM is a rapid and surprisingly easy
		way to quickly change any entries in the
		phone number library.  See M7LIB.DOC if
		instructions are needed.  M7NM-6.ASM is
		necessary for setting or altering numbers
		for 'SPRINT', 'MCI', etc.  It would also
		be better if making a lot of changes such
		as adding or deleting '1-' required for
		long distance dialing in some areas.
		
	NOTE:	If using the phone number overlay to change
		the phone library numbers, be sure to use:

			     M7NM-6.ASM

		The phone number library contains 36 numbers
		(A-Z plus 0-9)

     Most users will not need the lengthy (158k) source code at all.
     Just get MODM700.COM and then check one of the associated over-
     lay programs to obtain the overlay for your particular computer.
     Merge that with MODM700.COM according to the instructions near
     the start of the overlay file, using DDT.COM, etc.  (See above
     note relative to saving 73 sectors.  STAT.COM would then show
     146 records for 20k.)

     The following bytes can be changed easily with DDT, then SAVE 73

	0DFEH  -  HEXSHOW 00 = do not show hex record count
			  FF = show both hex and decimal count
	0DFFH  -  SAVSIZ  20 = 4k file transfer buffer size
			       (see table below for other options)
	0E00H  -  NUMBLIB (start of telephone number library)

     To change the file transfer buffer size via DDT, change byte 0DFFH:

		20   (hex)   =	 32 records   =   4k
		40   (hex)   =	 64 records   =   8K
		60   (hex)   =	 96 records   =  12k
		80   (hex)   =  128 records   =  16k

     (Use the largest value that does not give errors during file
     tranfers when the disk activates.  You have about 10 seconds
     before a timeout error would occur.  8" systems can easily
     handle 16k per transfer in 3-4-5 seconds.  5-1/4" systems are
     usually much slower.  In that case try 8k or 12k.  Default is
     set for 4k as that is known to work satisfactorily on all disk
     systems.) 

--end--
