Date: Tuesday, 25 December 1984
From: Robert L. Plouffe
To:   All
Re:   PAT700V2.ASM - patches for MODM700

PAT700V2.ASM allows patching of MODM700 for the following features:

	1.	Allow rubout to go to console and optionally
	eliminate the control character feature.

	2.	The UNDO-J option that restores terminal mode
	as the default at the calling end and command mode at
	the called end after completion of file transfers.  Yhis
	is how Ward originally wrote it and the preferred mode
	by many.

	3.	Corrected error that caused the wrong file to be
	erased (in some instances) when overwiting files in
	batch mode.  This patch was in PAT730Vx.ASM but did not
	make it into MODM700.

	4.	Allows for optional MAXWAIT times in the protocol
	to improve operation when operating with satellite
	communication links or with packet switched networks
	that can sometimes throttle and give excessive and
	variable packet delays.
