For those who would say that 8-bit CP/M is dead, I present the 
following edited exchange of messages from CompuServe...

--Keith Petersen <W8SDZ@SIMTEL20.ARPA>

------------------------------------
Dt: 17-Sep-85  01:49:43
Sb: A Z-SYSTEM Testimonial 
Fm: Peter O.E. Bekker 74106,1430
To: All

I have just now emerged from 10 grueling hours worth of eye-crossing 
(glossing) installation work - but am proud to report the SUCCESSFUL 
implementation of ZCPR3 and Echelon's ZRDOS on a Kaypro 4-84.  In 
short, a fully functional Z-SYSTEM.

Without qualification I can say the Z-SYSTEM is a MAJOR boon to 8-bit 
computing.

Rick Conn, Joe Wright and the folks at ECHELON are quite definately 
pioneers who have picked-up the ball from Digital Research and run with 
it...far beyond the goal post.  (At first blush this would seem silly -
who would want to run much past the goal post? That's probably what DRI 
asked itself..lo those many years ago.) Well - had DRI only answered 
its own question with the same kind of vision that made it famous in 
the first place, BIG BLUE and its conspirators might not have muscled 
it out of prominence so quickly and completely .. but I digress.

Initial "interfaces" with the Z-SYSTEM have shown a TREMENDOUS 
improvement over CP/M..most particularly in the areas of "friendliness" 
and functionality.  (It's MS/PC-DOS .. for those of us who don't much 
care for the EXPENSE of 16-bit computing.)

While I'd like to babble on & on about Z-SYSTEM - I can't..lest someone 
get the idea I'm enthusiatic about it..or (perish the thought) suspect 
I have an equity interest in the distributor.  (Wish I did.)

But to demonstrate my serious intent - I am preparing a comprehensive 
DOC file for installation of Z-SYSTEM on a KAYPRO 4-84 (for my own 
records) and will be more than happy to post it here should anyone 
express even the slightest interest.  It's not a breeze by any means 
but, when all is said & done, it is well worth the effort.  To 
paraphrase a once obscure music critic named Jon Landau who several 
years ago sat through a Bruce Springsteen performance at a small Boston 
club.. "I have seen the future of 8-bit computing.. and its name is
Z-SYSTEM."


Dt: 17-Sep-85  18:22:54
Sb: A Z-SYSTEM Testimonial
Fm: Eldor Gemst 74116,2714
To: Peter O.E. Bekker 74106,1430 (X)

Is there any HARDWARE installation required with ZRDOS or is it 
strictly software?  There must be alot of disk space required just for 
the system files - do you really feel the advantages of the system 
outweigh the disk space required?  I can see it on a hard disk system, 
but am less convinced with floppies.


Dt: 17-Sep-85  23:29:29
Sb: A Z-SYSTEM Testimonial
Fm: Peter O.E. Bekker 74106,1430
To: Eldor Gemst 74116,2714 (X)

You're right.  ZSYSTEM is a MUCH more noticeable boon on hard disks 
than floppies.  But there are considerable advantages on the smaller 
drives too.

As for file space..I've enjoyed a GAIN using ZSYSTEM.  First of all, 
ZRDOS is a direct BDOS replacement and takes up no more space than a 
machine's stock BDOS (even though it contains several significant BDOS 
enhancements.

Using ZCPR3, I no longer keep PIP or STAT on most disks, saving 14k 
right there.  Z3, as you know, has CPY and PROT to do most of the 
things PIP & STAT do.  The REQUIRED Z3 files that every disk should 
have are ENV (the environment), LDR (to load the environment..and other 
things) and RCP (the Resident Command Package.) They are 4k, 2k and 2k 
respectively.  So you see -by removing PIP & STAT (14k) I've freed-up 
8k of space per disk since the ZCPR3 residents total only 8k.

No hardware changes of any kind are required.  ZSYSTEM is strictly an 
operating system change...but as I mentioned to Charlie, I've just now 
gotten it running and will be reporting back periodically as advantages 
and disadvantages are observed.  I must say, though, that throughout 
the installation process, it became clear to me that ZSYSTEM is an 
intriguing and damn clever implementation.


Dt: 17-Sep-85  23:27:27
Sb: A Z-SYSTEM Testimonial
Fm: Peter O.E. Bekker 74106,1430
To: Sysop Charlie Strom 76703,602 (X)

The ZRDOS advantages that come immediately to mind are the extended 
function calls you'd heard about.  These include calls to set and reset 
a warm boot trap - a call to GET the current DMA.....ZRDOS also 
supports file archiving and wheel protection...You even get a DELETE 
key that works for command line editing since ZRDOS eliminates the 
troublesome ^R function.

The BIG convenience, of course, is AUTO DISK LOGGING (just like MS-DOS)
no more repetative ^C's each time a disk is changed..just take one out, 
put another one in .. and go.  The error messages are a lot friendlier 
(and more informative) too.

ZRDOS directly answers the complaints of those who say CP/M is too 
"unfriendly" to gain wider accpetance.  And for programmers, it's a 
dream come true..particularly teamed with ZCPR3.

Haven't benchmarked..not really set up for it.  ZRDOS is written in Z80 
so it's got to be a little faster that CP/M..though because of disk 
access slowdowns, probably not noticeably so.  But I guess a Ramdisk 
check could be made.

As for the vast CP/M 80 domain of programs..no reason why they can't be 
run under ZRDOS...

But I've just now gotten this running and I'll report periodically to 
the membership on what I find.


Dt: 17-Sep-85  23:24:55
Sb: A Z-SYSTEM Testimonial
Fm: Peter O.E. Bekker 74106,1430
To: John Deakin (CA) 74015,1624 (X)

Since ZRDOS is primarily a straight BDOS replacement, I will be 
concentrating [on writing] mostly (and in excruciating detail) on the 
installation of ZCPR3 in the K4-84. Included will be memory locations, 
sizes and uses...cold start patches for the BIOS, a change to lower the 
BDOS, a warm start patch to protect the CPR, step-by-step instruction 
on intstalling ZCPR3's main functions (ie External Path, Wheel Byte, 
Multiple Command Buffer.....in short, all the info I've been UNABLE to 
locate in the many ZCPR3 DOCs I've read.)

I hope to list all this info in such a way that even a total dolt such 
as myself would be able to make sense of it and even get Z-SYSTEM 
running while reading it.

--------------------------------

Peter Bekker's K4ZSYSIN.DQC is now available on most RCP/M systems.
