Date: Monday, 16 December 1985
From: Hal Bower
To:   Keith Petersen, W8SDZ
Re:   MCAT/XCAT Ver 5 release

Now available:

Filename	Type	 Bytes	 CRC

MCAT505.LBR	BINARY	100864  16D3H
XCAT502.LBR	BINARY	 81664  4053H

New Release     MCAT Version 5 Disk Cataloging Program
                XCAT Version 5 Catalog Cross-Reference Lister

   These two programs work as a team.  MCAT catalogs the directory of any
specified disk drive to a Master Catalog called MAST.CAT.  XCAT reads the
catalog and produces a cross-referenced listing of a selected set, or all
of the files to the console, printer or disk file.

   In addition to Filenames and Types, a disk ID is automatically appended
to each name in the catalog.  Optional fields can also be appended with
Version 5 to show the file's user area, and the created/modified date
provided by Plu*Perfect Systems' DateStamper(tm).  With Date features,
CP/M 2.2 is required.  If dates are not required, CP/M 3 should be useable.

   Major features provided in both MCAT and XCAT Version 5 are:

* Two-level operation; interactive screen-oriented mode, and one-shot "Expert"
  mode with parameters passed on the command line.
* Protection against corruption of MAST.CAT by conflicting operations
* Ability to pre-define default settings without reassembly, and to set new
  values interactively within the programs.
* Cursor and screen control definitions compatible with Plu*Perfect Systems'
  SETTERM utility for terminal installation.

   And some specific features:

MCAT - Create MAST.CAT in any drive/user area and enter "Ignore" names
     - Ambiguous as well as unambiguous "Ignore" names supported
     - Add a disk ID from within the program
     - Delete catalog entries for any specific disk by disk ID

XCAT - Search catalog and display only selected filenames, types or disks
     - Selectable destination for output filename, drive and user list
     - Display dates in US (mm/dd/yy) or European (dd.mm.yy) format

Authors:
        v 5.0   Harold "Hal" Bower
        v 4.??  Irv Hoff
        v 1.0   Ward Christensen

Bugs and revisions:
        Report bugs and suggested improvements to Hal Bower, or to
Bridger Mitchell at Plu*Perfect Systems.  In order to avoid a proli-
feration of minor changes, please do not publicly release revisions
of these programs.

DateStamper is a trademark of Plu*Perfect Systems.
CP/M is a trademark of Digital Research
