
Rare Gems <sm> August 1990
by David Wright

        Experience is the name everyone gives to their mistakes.
                --Oscar Wilde

        There are three ways to get something done; do it yourself, hire 
someone, or forbid your kids to do it.  --Monta Crane
 
        Don't go around saying the world owes you a living.  The world 
owes you nothing.  It was here first.  --Mark Twain
 
        Oh, Helen!  You're pregnant?  That's wonderful!...  At first, I 
was taking you quite literally when you said you had one in the oven.
        --One witch to another, "The Far Side"

        Nazis.  I hate these guys.
                --Indiana  Jones, "Indiana Jones and the Last Crusade"

        Hey!  I'm TRYING to pass the potatoes!...  Remember, my forearms 
are just as useless as yours!
        --Father Tyranosaurus Rex to family, "The Far Side"

        Tell the truth and you won't have so much to remember.  --
Unknown
 
        You can't depend on your eyes if your imagination is out of 
focus.
                --Mark Twain

        We can't all be heroes because somebody has to sit on the curb 
and clap as they go by.  --Will Rogers
 
        It is the anonymous "they," the enigmatic "they" who are in 
charge.  Who is "they"?  I don't know.  Nobody knows.  Not even "they" 
themselves.
        --Joseph Heller

	Burt Reynolds once asked me out.  I was in his room.  
-- Phyllis Diller

	He promised me earrings, but he only pierced my ears.  
-- Arabian saying

        I'd like to get married because I like the idea of a man being
required by law to sleep with me every night.  --Carrie Snow

        Look!  Behind ya!  Ain't that Lou Ferrigno?!
                --The Incredible Hulk to The Incredible Hulk,
                  "The Incredible Hulk" #373

        I am a marvelous housekeeper.  Every time I leave a man I keep 
his house.  --Zsa Zsa Gabor

        I take my children everywhere, but the always find their way 
back home.  --Robert Orben

        The man who invented the eraser had the human race pretty well 
sized up.  --Unknown

        I'm getting too old to hit attractive men over the head and 
carry them off.  And the sad part is, I'm so old that's the only way I 
can get them!            --Savil, "Magic's Price" by Mercedes Lackey

        You can't wash off blood with blood.  --Zen proverb

        If you're not going to kill me, I have things to do.
                --Colin Friels, "Darkman"

        I phoned my dad to tell him I had stopped smoking.  He called me 
a quitter.  --Steven Pearl

        At my lemonade stand I used to give the first glass away free 
and charge five dollars for the second glass.  The refill contained the 
antidote.
        --Emo Philips

        My schoolmates would make love to anything that moved, but I 
never saw any reason to limit myself.  --Emo Philips

        We've got to go -forward- to the future, and -past- to the... 
<struggled pause>  ...-back-.
        --Vice Pres. Dan Quayle, with broad gestures

        The guys came by to have some fun.  They'll come and stay all 
night, I fear.  But I know how to make them run.  I serve them all 
generic beer.
        --"Batch" strip (Marshall & Cravens)

        If women reaching their sexual peak at age 34 while men reach it 
at 18 is not proof that God is a woman, then I don't know what is.  --
Peter David

        I had a friend who told me he was tired of writing for nothing.  
He was going to go to California and write for money.  And he did.  He 
moved to California and I still get letters from him saying, "Please 
send me money."
        --Peter David

        The Pillsbury Dough Boy Serves Six will not be shown at this 
time...
                --"You Can't Do That On Television!"
 
        The Vegans.  They count MILK as meat.  EGGS is meat, CHEESE is 
meat, FISH is meat, BACON'S meat...  They won't even eat SPAM!
        --Christine's mother, "Big Numbers" #2 by Alan Moore

