This is a message I wrote to Carson Wilson on Lillipute Z-Node and 
wanted to share with the general CP/M public regarding his new 
program FILEDATE which I am testing, and which will be released, I 
believe, when the new NZCOM/Z3PLUS BDOS'es ZDDOS and ZSDOS are 
available.  FILEDATE is a directory utility with full datestamping 
support with an incredible number of command-line options that give 
the user the ability to sort by date in ascending or descending 
order, display only those files created (or accessed) on a certain 
day, etc. etc.  It's an excellent program the likes of which the 
CP/M-compatible world has not previously had.  Those with 
datestamping have a great deal to look forward to when the program 
is released.
         
                                  - Rick Charnes, June 3, 1988


Carson, it is absolutely extraordinary.  FDATE, that is.  Until I 
logged on here two days ago and got your message I hadn't used it at 
all.  Based on our phone call a few weeks ago I was under the 
impression that it wouldn't work on my Z8D3 system.  I _thought_ I 
remember you saying that when we had talked and therefore was just 
waiting till the new DOS was available.  When I got your message 
telling me about SAP, etc. though, I immediately went through the 
FDATE documentation and gave it a spin ... it's quite, quite 
marvelous.  I have wanted a program like this for some time, thought 
I was the only person to have such a desire (never heard anyone 
talking about it!) and am now pleased as punch at what you have 
created.  The incredible number and variety of command line options 
gives it a flexibility and power I hadn't even dreamed of.  
  
I mean, Jeez - I've been playing around a bit in the MS-DOS public 
domain and haven't found anything that can match this.  I would have 
to say that with FDATE, DATSWEEP, (UN)CR23D, Jay's new DateStamper- 
supporting ARUNZ09M which I'm beta-testing (which with its 
DateStamper-based parameterization is breathtaking in the fineness 
of what a user can do), SAVSTAMP, LBREXT26, LPUT15A, and many, many 
more (I know I'm leaving out a whole slew) along with DateStamper 
and Z80DOS generally we are fast approaching the point where we can 
quite honestly and simply say that our datestamping is superior to 
DOS's.  I have been mulling over in my head how this seemingly 
puzzling state of affairs -- that the datestamping of an obviously 
antiquated and useless operating system is superior to that of the 
popular OS -- can have come about.  
  
I have been tickled by the notion that it may be due, rather 
ironically, to the very fact that the DOSers have long taken 
datestamping for granted and have assumed that no improvement is 
necessary over what they have.  We, on the other hand, have had to 
work (very hard!) for it, and consequently have had to develop it by 
getting dirt between our fingernails.  We have made virtue out of 
necessity -- in the good, rather than sour grapes, sense.  We have 
had a number of superb programmer visionaries at work at it, 
constantly updating, refining, receiving and manifesting new ideas 
...
  
For instance, the fact that MS-DOS has no way of keeping track of a 
word-processed file's date of creation -- but more importantly ** 
that no one has ever *thought* to write the simple SAVSTAMP-like 
tool to do this ** -- has always been mind-boggling to me.  My 
theory is simply that they have 1) taken datestamping for granted, 
and 2) noticed that the DOS 'DIR' command just doesn't do it, ergo: 
a "c'est la vie" attitude --- and the idea just doesn't come to them.  
To those to whom I mention it the response is invariably, "Huh!  
That's a good idea.  I guess no one just ever thought of doing it."  
Yeah.
  
We, on the other hand, all come as fresh-faced brash innocents to 
this brave new datestamping world and are full of questions and 
excitement and quite impossible ideas, and are able to look at it -- 
and therefore program it -- in a new way.  Soon those impossible 
ideas somehow become reality...
  
Anyway, FDATE is superb.  I've been using it for an hour or two with 
no glitches.  The ability to specify all files created or accessed 
today is something that I have long yearned for.  Adding to this its 
ability to specify a date, sorting by date.... the list is endless.  
It takes a bit of getting used to, but I can see how displaying the 
date field as "..." if it equals the current or specified date/time 
is going to be very handy.  The help file is very nicely done as 
well.  You are to be greatly commended for a superb piece of work, 
and those using DateStamper-type stamps on their system have a great 
deal to look forward to when the new DOSes come out.  

As always, thanks for your continuing contributions.
