                     Z-node #58
          The General Store is Back Online
   
       ======================================
   
       Kent  Mason's  1Meg  Kaypro  is   back
       online.    Thanks  to  all  those  who
       called from out of state; your support
       is   appreciated  and  your   presence
       noticeable.
   
       The   General  Store  is  beta-testing
       DownLoad  Utility.   D/LU is a  remote
       utility   built  from  VLU  with   the
       additional  ability  to  invoke   file
       transfers from a list of tagged files.
       Call the Store and check it out.
   
       ======================================
   
       And coming soon from Z-node #58:  Even
       more powerful file transfer systems...
   
           Z-node #58, The General Store
                 sysop: Kent Mason
                 Oklahoma City, OK
           300/1200/2400 bps, up 24 hours
   
                    405-943-8638
   
       ======================================
