		      -*-   MultiCopy for Kaypros   -*- 
.
MULTICOPY - *FAST* format/copy/verify of almost all 5 1/4" soft-sector
	    formats (48tpi, 96tpi, SS, DS, SD, DD).  Database includes
	    some 80 formats (including IBM pc); new ones can be added. 
.
		includes, for Kaypros equipped with TurboRom:
.
TURBOSET  - Set any floppy drive(s) to another CP/M disk format.  Changes
	    the Kaypro's CP/M personality.  Uses no memory.
.
DOSDISK   - Set a floppy drive to MS-DOS (DSDD 9 sector) format.  Use
	    pc disks just like CP/M -- read, write, copy directly.  Uses
	    4K of memory as RSX.
.
From the authors of the TurboRom:        $39 (+ 6.5% tax in CA) + $3 s/h.
.
  Plu*Perfect Systems - Box 1494 . - Idyllwild CA 92349 - 714-659-4432
—Õê|µ $sÕÔ