Date: Wednesday, 10 June 1987  15:45-MDT
From: Dick Mead
To:   Keith Petersen, W8SDZ
Re:   ZEDUX...

Just chatted with one of the folks at Zedux. The BBS is expected to be
up by this weekend. He is still preparing docs for callers, the usual
housekeeping stuff. The BBS will use the Z280 in an old Cromemco
S-100 Z80 system.  The Z280 is a "co-processor" not too unlike the way
the various ad-on clock cards do, with the Z280 plugging into the Z80
socket, and the Z80 plugging back into the Zedux card. All parts are
soldered in, no sockets.  The design will accept 1 megabit Drams when
available, however.  Cost was a factor.  He says they did talk to
Echelon, but the software provided is their own, no plans to work
with Echelon.  The Z280 will have a 20mHz clock (10 mHz system clock)
and talks to the Z80 via an 8 bit port, the Z80 being an I/O
controller in this application.  He did talk to Ampro, too, but Ampro
will supposedly come out with their own single board Z280 card, and
Zedux says they will be doing likewise.  I am having some literature
mailed to see what else he may have in print.  No sources for the
system software are offered, not unlike CP/M CCP/BDOS.  It uses host
BIOS...Multiple programs see 64k, minus 512 bytes for system vectors
(page 0, Bdos/bios).

That's about all I got...If you call the service, the Zedux folks will
apparently call back...

Dick
