==The following appeared on ZNODE CENTRAL, 213-670-9465, and should
be of interest to all AMPRO LB users or would-be users.==
		Jim Bottom 4/19/90
 

Posted 04/17/90 at  9:10 pm by Moreland Hogan

To: ALL USERS     About: Smartclock (12 lines)

You don't have to buy the Ampro Smartclock (their minimum order is 
$100 these days, so you'd have to buy 2!) for the Little Board.
The "no-slot clock" from Delkin Devices, advertised in the back
page of BYTE, works fine (it's actually a Dallas Semiconductor
clock chip riding inside a 28-pin socketed holder). Use the 
(now public domain?) Ampro utility, AMPROCLK (in AMPROCLK.LBR)
to set the clock and thenset the bios clock from the hardware
clock. Terry Hazen's XCLOCK directly accesses the hardware clock
if you need precise timing. (Terry says the clock offered by
JRD is the same Dallas chip.) With ZSDOS this little clock becomes
a necessity (unless you like to set the bios clock each time you
turn on the computer).


Posted 04/17/90 at  8:56 pm by Moreland Hogan

To: ALL USERS     About: Ampro LB/Z80 (14 lines)

THIS IS GOOD NEWS: the Ampro LB/Z80 is not dead: it is now (as of 
about 2 weeks ago) being made by Davidge, an old player in the
Z80 single board computer business. I talked with Dean Davidge today
and he says they have 30 or so boards that came in the deal from
Ampro and are getting prices on fabrication of new boards. They
plan to maintain Ampro's price for the board (about $225).
Address & phone: Davidge Corp.
                 P.O. Box 1869
                 Buellton, CA 93427
                 805-688-9598
These are good people to deal with--they were pleasant and prompt
when I was resurrecting one of their 4/6DSB boards last year and
the quality of their boards is excellent. They do not mind dealing
with amateurs who only need a single board or even a part.

                           -end-
