Date: Thursday, 22 November 1984
From: Jesse Eaton
To:   Osborne Exec users
Re:   IEEE-488/CENTRONICS on OSBORNE

The following diagram should allow you to connect the OSBORNE EXECUTIVE'S
IEEE-488 port to a CENTRONICS port:

IEEE-488              CENTRONICS

1  ------- DATA0 (LSB) -----> 2
2  ------- DATA1 -----------> 3
3  ------- DATA2 -----------> 4
4  ------- DATA3 -----------> 5
13 ------- DATA4 -----------> 6
14 ------- DATA5 -----------> 7
15 ------- DATA6 (MSB)------> 8
16 ------- DATA7 (PAR) -----> 9
6  ------- STROBE* ---------> 1
12 ------- GROUND ----------> 19
8  <------ BUSY ------------- 11

NOTE: STROBE IS NORMALLY NEGATIVE GOING PULSE.
      BUSY LINE IS HIGH WHEN PRINTER IS BUSY.  THERE ARE PULLUP
      RESISTORS ON THE IEEE-488 WHICH PULL THIS LINE HIGH IF THE CABLE IS
      UNPLUGGED OR IS WIRED INCORRECTLY.


GOOD LUCK AND LET ME KNOW HOW IT TURNS OUT.  I STILL HAVE TO REWIRE MY CABLE
AS I TOO USED THE DIAGRAM ON PAGE 445 IN THE SYSTEM REFERENCE MANUAL.  WE
"ALL" KNOW THAT IS OUT TO LUNCH.

Jesse (all for better, more correctter documintasion) Eaton.


Date: Friday, 23 November 1984
From: Ronald Blanford
To:   Jesse Eaton
Re:   IEEE-488/CENTRONICS on OSBORNE

The IEEE 488 to Centronics wiring diagram you gave works like a charm.
There's still one minor problem unrelated to the wiring, and that's
that the Executive's BIOS times out occasionally when the printer is
busy and thinking that it's nonexistent asks if you want to deassign
it.  Answering "no" lets you continue just fine, but this is a
nuisance because it occurs quite often with my slow letter-quality
printer.  The timeout delay should be patchable, but I haven't looked
enough to find it yet.

Thanks, Ron


Date: Friday, 23 November 1984
From: Jesse Eaton
To:   All Osborn Exec users
Re:   OSBORNE EXECUTIVE PRINTER TIMEOUTS

The most recent version of the Osborne Executive Bios is V1.1.  It
allows you to set the timeout value for printers.  The SETUP.COM
program was also modified to reflect this.

Jesse (hacker isn't a dirty word) Eaton



Date: Friday, 23 November 1984
From: Jesse Eaton
To:   All Osborn Exec users
Re:   OSBORNE EXECUTIVE IEEE-488 PORT

The IEEE-488 port on the OSBORNE EXECUTIVE can be configured via a PIA
chip to communicate using the CENTRONICS or IEEE protocol to talk to
devices connected on that port.  If you plan on doing any serious
hardware hacking using it I would highly recommend the five manual
Technical Reference set.  They contain BIOS and ROM listings for V1.1
as well as tutorials on the schematics and chip sets.  The price is
steep however.  $125 + $18 (S&H).

Jesse (the librarian) Eaton
