Date: 3/28/83
From: Bruce Kargol
To:   All
Re:   Improved Kaypro config file for MDM705

I made a few mods to the Kaypro config file and have
uploaded it here.  Added ability to set for 600 and 9600
baud.  (Good @ 600 with some Smartmodems and 9600 for direct
connections).  Added clrscreen and clreos. Works fine. 
 
                                    Bruce.
