


                       CONTRIBUTION FORM FOR SIG/M LIBRARY

        NAMÅ Richarä Conn........................®  DATE.12../.10../.81..

        ADDRESS 4927 Woodman Pk Dr, Apt 10...............................

        CITY Dayton........................  STATE OH........ ZIP 45432..

        PHONE (513)-254-9492.......  CLUB AFFILIATION ACG/NJ.............

        NAME OF PROGRAM, PROCEDURE, OR MODULE (CIRCLE ONE)
          PROGRAM:  BDOSLOC
          MODULE:  ZCPR
        SOURCE LANGUAGE MAC Assembler...  HARDWARE REQUIRED Normal.......

        MEMORY REQUIRED 24K.......        ...............................

        DESCRIPTION OF WHAT IT DOES:

     ZCPR - Z80 Command Processor Replacement

     ZCPR is a replacement for the CP/M 2.2 CCP.  It is upward-compatable
with the CP/M 2.2 CCP, but provides several additional functions and
enhances other "standard" functions of the CCP.

     BDOSLOC is a program used to determine the Base Page Addresses of
the user's CCP and BDOS.  This is used to help integrate ZCPR into the
user's system.

        HOW TO USE IT:

     BDOSLOC is executed by typing 'BDOSLOC' after assembling; no input
parameters are required.  ZCPR is used as the current CCP is used.  Refer
to the enclosed DOC and HLP files for details.

ZCPR DISTRIBUTION DISK
XDIR II  Version 4.8, Vertical Listing by File Type
User Number:   0, File Attributes:  Non-System  

Filename.Typ Size K RS    Filename.Typ Size K RS    Filename.Typ Size K RS
-------- --- ------ --    -------- --- ------ --    -------- --- ------ --
BDOSLOC .ASM      2       DISK    .DIR      1       ZCPR    .HLP     14    
ZCPR    .ASM     51       ZCPR    .DOC     48       ZCPR    .WS      39    
DISK    .CRC      1    
B:     15 Entries &      7 Files -     85K Bytes Remaining
File Data:               7 Files -    156K Bytes Displayed

     Files:
          ZCPR.ASM - Source to ZCPR
          BDOSLOC.ASM - Source to BDOSLOC
          ZCPR.WS - WordStar Source to Documentation File on ZCPR
          ZCPR.DOC - Documentation File on ZCPRŠ          ZCPR.HLP - HELP File on ZCPR
          DISK.DIR - Directory of Disk
          DISK.CRC - CRC Values for Relevant Files

        PLEASE   ATTACH   ALL  RELEVANT  DOCUMENTATION  AND  A   DISKETTE 
        CONTAINING  THE  SOURCE,   ASSEMBLY/COMPILATION/LINKAGE   COMMAND 
        FILES, OBJECT CODE, AND ANY OTHER MACHINE READABLE DOCUMENTATION. 
        PLEASE USE THE FOLLOWING FILE EXTENSIONS:

               .ASM      .SOURCE FILE   OR .BAS, .Z80, .FOR, .COB, ETC.
               .DOC      .DOCUMENTATION OR .TXT, .ABS, ETC.
               .COM      .OBJECT CODE

        THE SUBMITTED FILES ARE IN THEIR PRESENT REVISION LEVEL,

              .... TO THE BEST OF MY KNOWLEDGE CURRENTLY IN PUBLIC DOMAIN

              .X.. UNDER  MY  DIRECT  CONTROL HEREBY PLACED  INTO  PUBLIC 
                   DOMAIN.  PERMISSION  IS  HEREBY GRANTED  TO  SIG/M  TO 
                   DISTRIBUTE THE FILES FOR NON-COMMERCIAL PERSONAL USE.

                         SIGNED.Richard Conn...................
                                   (Signed)

                         DATE.12/10/81.........................

        MAIL DISKETTE         SIG/M
        AND FORM TO:          P.O. BOX 97
                              ISELIN, NJ  08830






