;
;VRMAC --
;  MACRO ASSEMBLER "RMAC" CHANGES TO DISABLE 8080 OPCODES FOR CROSS-ASSEMBLY
;    WORK
; THIS PATCH WAS ORIGINALLY SUPPLIED WITH MY MAC MANUAL -- RLC
; MODIFIED FOR RMAC AND RESERVED WORD LIST 10/20/81 SHAWN EVERSON
;
;  THIS IS TO BE PATCHED INTO RMAC USING DDT.  AFTER THE PATCH IS COMPLETE,
;    PERFORM A "SAVE 53 VRMAC.COM" TO CREATE VRMAC.COM.
;
RT	EQU	25	; 8080 REGISTER NAME
PT	EQU	26	; PSEUDO OPCODE TYPE
TAREA	EQU	103H	; FREE AREA (REDUNDANT COPYRIGHT NOTICE)
TRAIL	EQU	'@'	; CHAR. TO REPLACE LAST LETTER OF RESERVED WORDS WITH
 
;
	ORG	2914H	; OVERLAY INXH - MOV B,M - RET
	JMP	TAREA
 
;
	ORG	TAREA
 
;  TYPE IS IN THE ACCUMULATOR
	CPI	RT	; BELOW RT IF ARITHMETIC OPERATOR
	JC	TYPEOK
	CPI	PT	; PSEUDO OP?
	RNZ		; RETURN WITH NON-ZERO FLAG
 
;  OTHERWISE, PSEUDO-OP OR ARITHMETIC OP
TYPEOK:
	INX	H
	MOV	B,M
	CMP	A	; SET ZERO FLAG
	RET
;
;LOCATION OF RESERVED WORD <IF>
;
	ORG	2606H
	DB	'I',TRAIL
;
;LOCATION OF RESERVED WORD <OR>
;
	ORG	2610H
	DB	'O',TRAIL
;
;LOCATION OF RESERVED WORD <AND>
;
	ORG	2623H
	DB	'AN',TRAIL
;
;LOCATION OF RESERVED WORD <END>
;
	ORG	2641H
	DB	'EN',TRAIL
;
; LOCATION OF RESERVED WORD <LOW>
;
	ORG	2659H
	DB	'LO',TRAIL
;
;LOCATION OF RESERVED WORD <MOD>
;
	ORG	265FH
	DB	'MO',TRAIL
;
;LOCATION OF RESERVED WORD <NOR>
;
	ORG	266BH
	DB	'NO',TRAIL
;
;LOCATION OF RESERVED WORD <SET>
;
	ORG	2696H
	DB	'SE',TRAIL
;
;LOCATION OF RESERVED WORD <ELSE>
;
	ORG	26C9H
	DB	'ELS',TRAIL
;
;LOCATION OF RESERVED WORD <HIGH>
;
	ORG	26D1H
	DB	'HIG',TRAIL
;
;LOCATION OF RESERVED WORD <NAME>
;
	ORG	26E1H
	DB	'NAM',TRAIL
;
;LOCATION OF RESERVED WORD <PAGE>
;
	ORG	26E5H
	DB	'PAG',TRAIL
;
;LOCATION OF RESERVED WORD <LOCAL>
;
	ORG	2718H
	DB	'LOCA',TRAIL
;
;LOCATION OF RESERVED WORD <MACRO>
;
	ORG	271DH
	DB	'MACR',TRAIL
;
;LOCATION OF RESERVED WORD <TITLE>
;
	ORG	2727H
	DB	'TITL',TRAIL
;
;LOCATION OF RESERVED WORD <COMMON>
;
	ORG	272CH
	DB	'COMMO',TRAIL
;
;LOCATION OF RESERVED WORD <PUBLIC>
;
	ORG	273EH
	DB	'PUBLI',TRAIL
;
;LOCATION OF SIGNON MESSAGE <CP/M MACRO ASSEM 2.0>
;
	ORG	319CH
	DB	'CP/M RMAC ASSEM 1.',TRAIL
;
; TYPE OF SOURCE FILE TO EXPECT
;
	ORG	2A4EH
	DB	'VOC'
;
	END



