El Paso, TX 12-03-82

Not even two weeks have passed and LMODEM gets "worked on"...
Nothing against that at all, BUT....

(This is my opinion on the subject, yours will probably differ)

1. I think the discovering and fixing of bugs in the early stage of
   this utility should definitely be of a high priority. Trivial
   changes should be made at a later stage, when it is known the
   program will perform as desired under all possible circumstances.

2. Anyone making changes and running DIF on the two files should
   always use the latest original distribution file, which must
   not have been modified in any way. I have just received a DIF
   file which SSED is unable to process. The original file will
   always be named LMODEMxx.AQM and will unsqueeze to LMxx.ASM.

3. I will not keep any "old" LMODEM files with the exception of
   version 1.0. If in doubt about the validity of a LMxx.ASM file,
   use 1.0 to make the DIF file.

4. Since updates, whether trivial or not, will within a short time
   be of a frequency similar to MODEM or XMODEM, I will not send
   out any AQM files. The file LMODEMxx.AQM (latest version is 13)
   will always be on the El Paso RCPM (915) 598-1668.

5. I believe LMODEM is fairly bug free and unless I see a serious
   bug I will not update it.

6. Since this program is fully in public domain, feel free to do to
   it whatever you think is necessary. When making major modifications
   to the file, please be sure not to remove the credit line, especially
   in regards to the writer of the original XMODEM program, since
   LMODEM is directly derived from XMODEM. Regardless of updates I
   personally consider only the file on my RCPM to be the latest
   valid file, so please let me have your contributions. Note that
   if for whatever reason SSED fails when I use it, I will manually
   key in the changes if at all possible, thus changing the CRC of
   the new version.

7. Good hacking!

