GEnie Mail follows:

Date: Sunday, 15-Jun-86 10:23:00 EDT
From: Bill Duerr - CP/M SysOp <B.DUERR>
To:   Keith Petersen - CP/M SysOp <W8SDZ>
Sub:  KAY256.LBR

File 1632, KAY256.LBR, Library 18 of the CP/M RoundTable, contains
details on adding 256k of RAM to the Kaypro IV computer (pre 1984
model) by installing 256k chips in place of the 64k chips.  It
applies equally to Kaypro II's that contain a IV motherboard.  The
design can be used with any 8 bit computer that uses 64k dynamic
RAM.

This library contains detailed instructions, the circuit schematic
diagram, and benchmark results (gives an idea of benefits likely on
disk intensive activities).

No software is included here but if you wish to construct this for
a Kaypro, the author has written a BIOS that supports the RAM as a
ramdisk under ZCPR3 and offers it for the asking.

The library has been downloaded from The DataCOM Super Systems(tm)
(see JUN86.MQG for information how to access this system), which in
turn came from a caller in London England who only calls once or
twice a month.

Steve Sanders advises that he does not as yet have the altered BIOS
code mentioned in the DOC file.  It will be available on his BBS as
soon as he gets it.  He did however get the address of the author.
It is:

   Dr. Michael W.D. Liddle
   21 The Frostings
   Grenoside
   Sheffield, S30 3NZ England

If you make this modification, please provide feedback in this BB
section.
