Date: Friday, 16 November 1984
From: Hugh Redelmeier
To:   net.micro.cpm
Re:   Need Kaypro technical help

I have done serial I/O on the Kaypro II (pre-1984 version) using
interrupts.

- Only the first 16K of address space is bank switched.

- Remember to put your interrupt routine and the vector above 16k.

- You must use the interrupt mode that allows you to
  specify that the interrupt vector is above 16k.

- If you are using PluPerfect CPM2.2E, it is already using
  interrupts with the SIO (using the SIO channel to the keyboard
  as a timer to turn off the disk after a few seconds of inactivity!).
  It would be tricky to share the SIO interrupts with CP/M 2.2E.

- Be careful to use very little stack in your interrupt routine:
  the interrupted routine may not have left you much.  Best to
  switch to a private stack immediately on entry to your
  interrupt routine.



Date: Saturday, 24 November 1984
From: Mike Rubenstein
To:   net.micro.cpm
Re:   Need Kaypro technical help

On the Kaypro 10 the first 32K is bank switched.
-- 
Mike Rubenstein, OACB, UT Medical Branch, Galveston TX 77550
