Kaypro owners may find this of interest.  I found this message
on TCBBS Dearborn.  It's almost a year old but may still be
valid.
--Keith

Date: 06/24/83
From: DAVID WILLIAMS
To:   ALL KAYPRO USERS
Re:   NEW KAYPRO BBS

     Non-Linear Systems(Kaypro) would like to announce
the establishment of a new Computerized Bulletin Board
and Software Exchange to better support Kaypro owners. 
The telephone number of this system is:  (619) 481-3942
 
      This system is available 24 hours a day, 7 days a
week for your use.  The BBS is maintained by members of
the Technical Support Group at NLS and any questions
left on the BBS will be answered to the best of our
ability.  Remember, the only way for something like
this to become valuble is for you (Kaypro owners) to
call in and involve yourselves.  If you have any ideas/
programs/questions please call them in.  We hope this
becomes a big success.
             Thank you,
             David Williams, Kaypro Tech Support Group
