[ Captured from The ZCPR3 BBS/Z-NODE CENTRAL - Jun 25, 1986 ] 

Msg #6612 posted 06/22/86  by Ken Davidson
To: Rick Charnes     About: Micromint (12 lines)

Rick,
    Are you familiar with Steve Ciarcia of BYTE magazine?  Micromint
markets and supports the projects he writes about in his articles.
Take a look at the September/October 1985 issues of BYTE for a
description of the HD64180 and the SB180 which uses it.  The chip
is basically a super Z-80 with an on-board MMU, DMAC, 2 serial ports,
internal timers, etc.  We (yes, I work there) run the Circuit Cellar
BBS to support customers (203/871-1988).  If you want more information
about the company, call the BBS or our toll-free number (800/635-3355)
and ask for a catalog.  (That wasn't too commercial, was it Dave?)
 
                                         Ken

Msg #6619 posted 06/23/86  by BRUCE MORGEN
To: Rick Charnes     About: micromint (20 lines)

Rick, the Micromint SB-180 is the first of a new generation of
CP/M-compatible computers bundled with full-up Z-System (Z3 plus
ZRDOS).  Instead of a Z80, it's built around Hitachi's HD64180,
an all-CMOS microprocessor that, for all intents and purposes, is
fully compatible with existing 8080/8085 and Z80/NSC800 programs.
It is fast - currently 6.144 mHz, with faster parts already in the
Trans-Pacific pipeline.  Because of improved microcoding, the 64180
is faster than a Z80 running at the same clock speed - to the user,
a 6.144 mHz 64180 `looks' like about 7.5 to 8 mHz in Z80 terms.
The SB180 is a very good (NOT perfect - first shots seldom are)
microcomputer, discernably faster and more refined than a Morrow or
Kaypro (especially when using the VERY rapid 190k ramdisk).  On the
down side, the SB180 has a rather large BIOS, all of which resides
in the "user bank" of memory.  This makes the TPA with the stock
Z-System a bit skinny by Kaypro/Morrow standards: it has a 56k
system size - a similarly full-up (w/IOP) system on a floppy-based
Kaypro is 2k larger.  This has given very few users problems, but
NAOG will be supplying a bigger (59.5 to 60k) system without IOP
and RCP to support the few in need.  Hope this addresses your
question.  NOW will you drop the absurd notion of running MESS-DOS?
